---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-triggers-raw
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: tekton-triggers-raw
  healthChecks:
    - kind: Deployment
      name: tekton-triggers-controller
      namespace: tekton-pipelines
  timeout: 3m0s
  dependsOn:
    - name: infra
    - name: tekton-pipelines-raw
...
