apiVersion: apps/v1
kind: Deployment
metadata:
  name: tss
  namespace: tss
  labels:
    app: tss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tss
  template:
    metadata:
      labels:
        app: tss
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: mkdir
        image: docker.io/library/busybox:1.36.1
        securityContext:
          runAsUser: 0
        command:
        - sh
        - -c
        - |
          mkdir -p /data
          chown -R 1092:100 /data
          chmod -R 755 /data
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: tss
        image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:0.7.1
        # override to start the tss as not privileged user, and to use a read-only root filesystem
        command: ["/bin/taskchampion-sync-server"]
        securityContext:
          runAsUser: 1092
          runAsGroup: 100
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        env:
        - name: RUST_LOG
          value: info
        - name: DATA_DIR
          value: /var/lib/taskchampion-sync-server/data
        - name: LISTEN
          value: 0.0.0.0:8080
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: tss-envs
              key: TASKCHAMPION_SYNC_SERVER_CLIENT_ID
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /var/lib/taskchampion-sync-server/data
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tss-data
