apiVersion: v1
data:
    TASKCHAMPION_SYNC_SERVER_CLIENT_ID: ENC[AES256_GCM,data:GksCjsOrHsx4bJPcE66pj6dLqrOsifUE73iFRJTiNDlza1x983C0oSDrEQn2Z111fYMfqbCe4JIgdiJ2OLaG2dmxZVkYy2MqdwRfT1YxMpWtpEG+eGCWp2Dc9wNR20czTEHLkw==,iv:FFquzBk9XlVTxei9t28t49J1Rn7PW9X2ZhkgJtcERjw=,tag:p+P134kwix4NOiFaoYvMUA==,type:str]
kind: Secret
metadata:
    name: tss-envs
    namespace: tss
sops:
    lastmodified: "2026-06-28T14:30:49Z"
    mac: ENC[AES256_GCM,data:EcUuYhCUusW8W3/N4vDLiXdaw5rY5EgOsk0XU5uc1BLzzaH+uFDoDoGyVD5EMZTBm2qR+Bv0KIPUkXPV0Xpqpysb23V3ROcRccU1r4wwmupsBRciT78uFa9Pmb5LXubgHNTroUjBNoyaKxtdKlSkBhUPZ/vbTCU7f7TPVbfc6GI=,iv:D9Mh85oGP6kS2M5+FWGtY6YdI8WfKRmiYfpjzR9bXqk=,tag:w1ohPSvBQiOYaXAyQfGbvQ==,type:str]
    pgp:
        - created_at: "2025-08-02T22:12:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+JdfTByuVb7IBsBWGV9bVraBoB6WUm3TWyvsJdpvk1/+r
            hli78S9SJkj07/pG/R4ROgvtW1b/2aRtM1WSg/xSOhkwlIDmbRvEtlrFaWckn6nq
            5sHJ9aI/CzlNGeFgRxWXp+EijEl/lOBxPcjCs9CPzSb4Fb7h6/gt5i3/2h01dQe4
            pZS6Dwi9vol2Ve3VdJlZQAWBVwil8U7GbeuJhnIKV90W0TPFyWmecgsW1g+3CP+7
            CrkiNsa7nuMWFH4vzyZsZkG2ao5aggcnRS+AhC5Gu3bjuZ2ZfcbpbQobG5Xf+DwW
            OAniY8CzDBgyNCsm2l7+Dqth8o7d0WaL/E2lJiBcX3USMkP2JBLpX5ITIx0fW9qd
            Jz2wfNqX/c9xRNn+iyOv8uZ3ssWMZJn3iI5EROrUDu7OhSwb5Rt+3BO/36ep7ldW
            xoYM/4m+vFHCQdLrW0P9pybtCftXacqyolxErF6OLgzDLD06ID0zqMgj6nUo2pkE
            n755UzX8+RqweegGs01mQvhiym25LFbWKjepzJJP0l3GSIORwQ7bxSTLsOWhX9Ge
            0tgkJaZOL2jXSLU3RJo9j8vFx8wlhsoy+peYYKQHYjpF8TvtgvPE3oA/5FKEpFZD
            jGwzUyp/Vtl61HzZbRs/ShxVMxNGF7yIneQzY21CMNh1QxpsoL2FigdVvmUdwinS
            WAEYD2oKc+qZj6Vvtf3Xzt7tVnhHmJGNg8Ys7dmeoFPXRrq5OF7FsTEJ1UE8SrXI
            CSUS9c/sen3ia308xS7w1he5KCPEi8o3rYWxcvnGYcNzNbMfye11AL8=
            =0E+r
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.11.0
