apiVersion: v1
data:
    TASKCHAMPION_SYNC_SERVER_CLIENT_ID: ENC[AES256_GCM,data:yHATd5ldGqW/EbR/QxxjkuW3+eItQmSsqPtOULTFfli6ITY0UwfPQ6ATinz4fn2f,iv:F09nsOdnltKMJiBgGhc0xFUAN9vGbDGlKRQNWSrnGVY=,tag:IdnPOXOEHaycMEz4szYVLQ==,type:str]
kind: Secret
metadata:
    name: tss-envs
    namespace: tss
sops:
    lastmodified: "2026-06-15T15:44:10Z"
    mac: ENC[AES256_GCM,data:3yiI5hsiqiuTicaLPpX+YgVZA0Dd377a1EYFEFY84d36sqorVSPQA972weggz1PT934FKMfB2UmQiCyLyyMvgh4WaSon8czj4LyiWC2SU5+Btio5CMqpHA6wPnUlRiw1lLE8jyoMVwKwMORnLcMfyyg61M6eDmDR6A3vXwktHDI=,iv:GibS9GjUTLCtfu0jCzSBxSi3EaJU/aEUXCDCXcB2Naw=,tag:TOILPxXfluVdGKy/LC1W5Q==,type:str]
    pgp:
        - created_at: "2025-08-02T22:12:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+JdfTByuVb7IBsBWGV9bVraBoB6WUm3TWyvsJdpvk1/+r
            hli78S9SJkj07/pG/R4ROgvtW1b/2aRtM1WSg/xSOhkwlIDmbRvEtlrFaWckn6nq
            5sHJ9aI/CzlNGeFgRxWXp+EijEl/lOBxPcjCs9CPzSb4Fb7h6/gt5i3/2h01dQe4
            pZS6Dwi9vol2Ve3VdJlZQAWBVwil8U7GbeuJhnIKV90W0TPFyWmecgsW1g+3CP+7
            CrkiNsa7nuMWFH4vzyZsZkG2ao5aggcnRS+AhC5Gu3bjuZ2ZfcbpbQobG5Xf+DwW
            OAniY8CzDBgyNCsm2l7+Dqth8o7d0WaL/E2lJiBcX3USMkP2JBLpX5ITIx0fW9qd
            Jz2wfNqX/c9xRNn+iyOv8uZ3ssWMZJn3iI5EROrUDu7OhSwb5Rt+3BO/36ep7ldW
            xoYM/4m+vFHCQdLrW0P9pybtCftXacqyolxErF6OLgzDLD06ID0zqMgj6nUo2pkE
            n755UzX8+RqweegGs01mQvhiym25LFbWKjepzJJP0l3GSIORwQ7bxSTLsOWhX9Ge
            0tgkJaZOL2jXSLU3RJo9j8vFx8wlhsoy+peYYKQHYjpF8TvtgvPE3oA/5FKEpFZD
            jGwzUyp/Vtl61HzZbRs/ShxVMxNGF7yIneQzY21CMNh1QxpsoL2FigdVvmUdwinS
            WAEYD2oKc+qZj6Vvtf3Xzt7tVnhHmJGNg8Ys7dmeoFPXRrq5OF7FsTEJ1UE8SrXI
            CSUS9c/sen3ia308xS7w1he5KCPEi8o3rYWxcvnGYcNzNbMfye11AL8=
            =0E+r
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.11.0
