apiVersion: v1
kind: Secret
metadata:
    name: tss-backup
    namespace: tss
    labels:
        apps.gitops: tss
type: Opaque
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:bED9aXz7nxRyltJYQHwcQo+R/i16Hah/VpBnUw==,iv:DYHiSTkx4MX1WfyeT1NciWXQxpe1WH236kgAzNDgG3g=,tag:jD9KTl/2uJ7QAXwNJ/253A==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:a7upqMeZO+X4DKuYEHAG,iv:NAfXLxPWGVDJ+69mJcbqcEXuGeK3vpIqUxl18eAhg0I=,tag:JKqhZjBpxHNooWNLSZD3eg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:LH78m6leVrTmSycVJBat1Tx1,iv:n9wuUZWxYbMxBrck8mOS2pq5X6uFUIavy+XsIhxwZjs=,tag:gY6y7yR/4xQAoyTzLr1t9g==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:wu1s+4JatL7QFg==,iv:duxB7S9s7rmUFBzskWuOMgerL8z6NbueP45x4uTwqQ8=,tag:4DrcAj0DHKq5HLCFZJ75Wg==,type:str]
sops:
    lastmodified: "2026-08-30T09:44:36Z"
    mac: ENC[AES256_GCM,data:KOeufsiS4RaThke91QSdYK1KKrJNQ+4uYw4SVsyAV+ZnJ7CRtCRkr1frSNrSglZvFwfpA4fXTvfNwfbGLVpNw1lWkHgg1iy/V8tA8tGMv5Y+d108zJVEIDU0Vxz8u1byVP72IyU968QdvgCECd5WiiXKMMamx7Sa6APfPjC50hU=,iv:UhL1pVGhpLdeEpwh5wbC2OVj3AJ7OiqqeAoAIc3p+5k=,tag:b8Do6AT3fnOj8DXXHaMM7Q==,type:str]
    pgp:
        - created_at: "2026-08-30T09:44:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//WpMzudLK+90UrJMyT3NVKGxeN/cd3LKVoJwb5kQgWie0
            IGZJGo/FejaqA0N6RU4SLk5viaWYwv6oyupSiAee+KSpPAvHbMcyZvIpN0qo0Dz7
            w6nbxUTKNIPfLdM8Rxu+FuGxln/NQUZozo27DNheTmNXWFzoBX1CD8XdMPhDWlpf
            z28cKC+wV/YFLT3wtozCrpSsBmy1JCtWcNvlmIt2WOt/U7913A+1bnKnGXxNqQdY
            nJb4eP+EOqkBib4Y3YGYfW8q1WV5S418raICr/uN5clTwGLbe2Ngmg8Ypfv5j+4r
            kmmegceEIw3VtlPaSm3rtg768uMedeGZcAgp+T3nL8m6s2n2TZe+NxWpusgcTV6l
            aJGWD+8QE6yorcH82zeyLh0fQGh4DHw6iwi2faZu1MqLgtHc2J3B0simDilI1ylE
            3faVy2ClzTWWJUJ/b5LAv1spb9q8c6Ywl2CrA9Qzs6EI442U9N3CxM4zZ7o2oMds
            hFEcKUd/vX/HuCrNapNt6Gr5x5yaaIj1HdHqSkQsMz1ZE6SG+552+pdIE+T2QO0b
            xz5E3GagaKm5yumm9usFA9Jd8FRMsZ2/1opQKVNIy9Ork5hpSUftKgrE9eLDAmSH
            fMXwH5Y728TTOjanstpuiiodHsIGo+1xEkspQI/KXrITBWSU/LTN6urNuldNqZ/S
            WAFvRQvYfZbP0y+tzeCAqkK5IWZS9uaTpDULC7ZdiR1yuXDddCDGLn1n3BHVu+/Y
            9YsYQFK5Z9Zq9kmgIh1tztRRMKUQ1ufP+T9mhlGcGNsGfIgS1PH9Ba4=
            =LAbQ
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
