repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-json
  - id: check-yaml
    args:
     - --unsafe

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 9b9df9f1d3bd9a5e7a52d8f61a3be3e29e73d127  # frozen: 0.33.3
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
    - id: check-dependabot

- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: bc51435089e5bc665a78cb53136f6403f00773e8  # frozen: v2.1.1
  hooks:
  - id: forbid-secrets

- repo: https://github.com/brokenpip3/pre-commit-hooks
  rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
  hooks:
    - id: github-actions-hash
      files: ^.github/workflows/.*\.(yml|yaml)$ # limit only to github workflows
