apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: promtail
    namespace: promtail
spec:
    interval: 10m
    releaseName: promtail
    chart:
        spec:
            chart: promtail
            version: '>=4.2.0 <5.0.0'
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: flux-system
            interval: 10m
    values:
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      defaultVolumes:
        - name: pods
          hostPath:
            path: /var/log/pods
      defaultVolumeMounts:
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
      serviceMonitor:
        enabled: true
      config:
        lokiAddress: http://loki:3100/loki/api/v1/push
