apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: loki
    namespace: loki
spec:
    interval: 10m
    releaseName: loki
    chart:
        spec:
            chart: loki
            version: '>=2.11.1 <3.0.0'
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: flux-system
            interval: 10m
    values:
      persistence:
        enabled: true
      rbac:
        pspEnabled: false
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      serviceMonitor:
        enabled: true
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 36h
        ruler:
          storage:
            type: local
            local:
              directory: /tmp/rules
          rule_path: /tmp/scratch
          alertmanager_url: http://prom-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
          ring:
            kvstore:
              store: inmemory
          enable_api: true
          remote_write:
            enabled: true
            client:
              url: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9093
