apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: loki
    namespace: loki
spec:
    interval: 10m
    releaseName: loki
    chart:
        spec:
            chart: loki
            version: '>=6.18.x <7.x.x'
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: flux-system
            interval: 10m
    values:
      deploymentMode: SingleBinary
      singleBinary:
        replicas: 1
        resources:
          limits:
            cpu: 1
            memory: 3Gi
          requests:
            cpu: 1
            memory: 3Gi
        extraEnv:
          - name: GOMEMLIMIT
            value: 2750MiB
      memberlist:
        service:
          publishNotReadyAddresses: true
      chunksCache:
        writebackSizeLimit: 10MB
      lokiCanary:
        enabled: false
      gateway:
        enabled: false
      test:
        enabled: false
      backend:
        replicas: 0
      read:
        replicas: 0
      write:
        replicas: 0
      ingester:
        replicas: 0
      querier:
        replicas: 0
      queryFrontend:
        replicas: 0
      queryScheduler:
        replicas: 0
      distributor:
        replicas: 0
      compactor:
        replicas: 0
      indexGateway:
        replicas: 0
      bloomCompactor:
        replicas: 0
      bloomGateway:
        replicas: 0
      loki:
        commonConfig:
          replication_factor: 1
        schemaConfig:
          configs:
            - from: 2024-04-01
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        ingester:
          chunk_encoding: snappy
        tracing:
          enabled: false
        querier:
          max_concurrent: 2
        storage:
          type: filesystem
        auth_enabled: false
        rulerConfig:
           storage:
             type: local
             local:
               directory: /var/loki/rules
           alertmanager_url: http://prom-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
           wal:
             dir: /var/loki/ruler-wal
           remote_write:
             enabled: true
             client:
               url: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9093
