---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton-operator-raw
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/brokenpip3/tekton-operator-raw-manifests
  ref:
    tag: v0.23.0-2
  ignore: |
    .github/
    hack/
...
