---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metric-server
  namespace: kube-system
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: '5.10.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    apiService:
      create: true
    extraArgs:
      kubelet-insecure-tls: true
      kubelet-preferred-address-types: InternalDNS,InternalIP,ExternalDNS,ExternalIP,Hostname
      logtostderr: ""
      v: 2
...
