apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-metric-server.yaml
- helm-nginxinc-ingress-controller.yaml
- helm-certmanager.yaml
- secret-certmanager.yaml
- storage/helm-nfs-storage-class-source.yaml
- storage/helm-nfs-storage-class-release.yaml
- utils/cronjob-etcd-backup.yaml
- prometheus/
#- tekton-operator/tekton-operator-source.yaml
#- tekton-operator/tekton-operator.yaml
#- tekton-operator/tekton-operator-crd.yaml
- tekton-pipelines/tekton-operator-source.yaml
- tekton-pipelines/tekton-operator.yaml
- utils/cronjob-pipelinesrun-cleanup.yaml
- utils/cronjob-taskrun-cleanup.yaml
