apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-metric-server.yaml
- helm-nginxinc-ingress-controller.yaml
- helm-certmanager.yaml
- secret-certmanager.yaml
- storage/helm-nfs-storage-class-source.yaml
- storage/helm-nfs-storage-class-release.yaml
- utils/cronjob-etcd-backup.yaml
- prometheus/
- tekton/tekton-pipelines/tekton-pipelines-source.yaml
- tekton/tekton-pipelines/tekton-pipelines.yaml
- tekton/tekton-triggers/tekton-triggers-source.yaml
- tekton/tekton-triggers/tekton-triggers.yaml
- utils/cronjob-pipelinesrun-cleanup.yaml
- utils/cronjob-taskrun-cleanup.yaml
