apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-metric-server.yaml
- helm-nginxinc-ingress-controller.yaml
- certmanager/helm-certmanager.yaml
- certmanager/secret-certmanager.yaml
- storage/helm-nfs-storage-class-source.yaml
- storage/helm-nfs-storage-class-release.yaml
- prometheus/
- datastores/helm-postgres-zalando-operator-release.yaml
- datastores/helm-postgres-zalando-operator-source.yaml
- utils/
- loki/
