apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-ovh
    namespace: cert-manager
spec:
    acme:
        email: ENC[AES256_GCM,data:A95gl0Yc/NZZarZneHkNkc3DJX4=,iv:Fux5Ytp0WgWnSpDEQQmbLy+v2eeHKdb2ERTCI7xoOnA=,tag:xLC9B2wsjE3kdV03oS7ukQ==,type:str]
        preferredChain: ""
        privateKeySecretRef:
            name: letsencrypt-ovh-account-key
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                webhook:
                    config:
                        applicationKey: ENC[AES256_GCM,data:MLfSWIh1OytBvpDdJx1PsA==,iv:k9Oi1ucunhqkYDSHHtI4sxsHkpMgShGJBszGH4QOw2w=,tag:jE74GOpZIFVOuQJFJRnlSA==,type:str]
                        applicationSecretRef:
                            key: applicationSecret
                            name: ovh-credentials
                        consumerKey: ENC[AES256_GCM,data:mWxJR766aT0ixW1H4anTQQnL1WqXJrjaZKG90azJXqY=,iv:y8od16XRIn9jlJGPdCh351X8aAQKL7ZJI1jGyK96F/c=,tag:ZYl7cf0YrBwAuxMNcDOqow==,type:str]
                        endpoint: ovh-eu
                    groupName: ENC[AES256_GCM,data:K0dfzuI1eM0fhWHVKUVDHFo/AIJD0Io=,iv:BU8Tq4Z43YKoeRbgaK6GmEz2z63d2oCNx6xbxmbSrOk=,tag:225wArwObPbao+uzAavV3A==,type:str]
                    solverName: ovh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-01T22:30:46Z"
    mac: ENC[AES256_GCM,data:B8ay+8j1jADPANcxH/qV8k4Ac1vlgpBwWQpao/U7xFZb7+1UkASBbCAJNBd+zlr9kIEimj2+M/ye1Qg4Hc/BfYZt/CDl5YzNyTibYvsCCzOZqTfd/v85rrJE8wbaA0PhagAyOHJsvLNwTh4/UmraQ8eifjDySCkevFPgWf0+dFE=,iv:ss+qdVLsULTAEMJiUaBg4G7FJV0YtduFRSpouwc4fEM=,tag:YWqK6J7lwWRmsprmGhpwCg==,type:str]
    pgp:
        - created_at: "2021-07-01T22:30:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//aSBINfVWOMXVDX9mJQoGkTWvo/EeqxmBdVxJIa4J/Y94
            NS0vHnKGIEyHY44yOxdiyx/5NEQ0XeOvBpmOx7kXPMbw2oM+eXawt9oucczAdL2K
            UH20CH8INqFGccO/EVnkO1O2FW/SBhqufbOWmBc7I1waXd+WJV4zduH1XaRGxWz2
            bh/li+qb6iryHsWVFnWDBx1No29mH5jKp0UoL/pfRzUZ6NiFCbIWQ4YRLVlSClca
            w7WY69jMAirLT8i4XHVshJ4nG6urYrePC0nWQhQY3g1L9mI9bUTox17hnHH4B9he
            8I37jUnuHXaD1V8PDVARs89hFu4ITfyLawx2vizSqqYI7ZKoyuBzj2S3Imf3SJ2f
            yejaaNEFOvf84Pwg4CNWMWFr2xyeW8LtlrR3LkY7IcAys2OjE+LWDR0Nr9LVskOe
            UzlQAG2dc7FAinH1KXFrhVkBX0cc6ZZ/TrwR9siQ+DDyvcpfe2WncMrMqREd2kB6
            SCIe5biSxzQUFrgrQa+iKXXhRxMDxHabUh1j+IpwaSfKDU8kfIGKI04RELGTFrTH
            OqFBrY2QGgk3nbJGaKKGTzU7Nu1YhHF4veXlBYK8XCP6KFkcAyu8kCW+rS6sfFOI
            DZ4M49QGCXJg5FZNtmMs581ileZ7OfalZd51soveomJsdPPwBt7yga+FuIrNjorS
            TgETy6IqEXJtsTVXhwJVcQGgxunzgNovMulXh3ZCRwC4K0Q3IIzuasdYKtwPHvLy
            1bKD0xPJeBzKG7vaLqF/bvBtvfTz3svzex2IXdL1yg==
            =X3zh
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    applicationSecret: ENC[AES256_GCM,data:76sSqxdw8vmvbuD4xzrAR3M/Qsq/mrqXQcOOTvxIkME=,iv:+CJRMf4lUykRA7hEgtfCBokSqVivmDiPIXvZA1d+/xw=,tag:LcGB0uaPosuSnlgRfm+joQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-01T22:30:46Z"
    mac: ENC[AES256_GCM,data:B8ay+8j1jADPANcxH/qV8k4Ac1vlgpBwWQpao/U7xFZb7+1UkASBbCAJNBd+zlr9kIEimj2+M/ye1Qg4Hc/BfYZt/CDl5YzNyTibYvsCCzOZqTfd/v85rrJE8wbaA0PhagAyOHJsvLNwTh4/UmraQ8eifjDySCkevFPgWf0+dFE=,iv:ss+qdVLsULTAEMJiUaBg4G7FJV0YtduFRSpouwc4fEM=,tag:YWqK6J7lwWRmsprmGhpwCg==,type:str]
    pgp:
        - created_at: "2021-07-01T22:30:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//aSBINfVWOMXVDX9mJQoGkTWvo/EeqxmBdVxJIa4J/Y94
            NS0vHnKGIEyHY44yOxdiyx/5NEQ0XeOvBpmOx7kXPMbw2oM+eXawt9oucczAdL2K
            UH20CH8INqFGccO/EVnkO1O2FW/SBhqufbOWmBc7I1waXd+WJV4zduH1XaRGxWz2
            bh/li+qb6iryHsWVFnWDBx1No29mH5jKp0UoL/pfRzUZ6NiFCbIWQ4YRLVlSClca
            w7WY69jMAirLT8i4XHVshJ4nG6urYrePC0nWQhQY3g1L9mI9bUTox17hnHH4B9he
            8I37jUnuHXaD1V8PDVARs89hFu4ITfyLawx2vizSqqYI7ZKoyuBzj2S3Imf3SJ2f
            yejaaNEFOvf84Pwg4CNWMWFr2xyeW8LtlrR3LkY7IcAys2OjE+LWDR0Nr9LVskOe
            UzlQAG2dc7FAinH1KXFrhVkBX0cc6ZZ/TrwR9siQ+DDyvcpfe2WncMrMqREd2kB6
            SCIe5biSxzQUFrgrQa+iKXXhRxMDxHabUh1j+IpwaSfKDU8kfIGKI04RELGTFrTH
            OqFBrY2QGgk3nbJGaKKGTzU7Nu1YhHF4veXlBYK8XCP6KFkcAyu8kCW+rS6sfFOI
            DZ4M49QGCXJg5FZNtmMs581ileZ7OfalZd51soveomJsdPPwBt7yga+FuIrNjorS
            TgETy6IqEXJtsTVXhwJVcQGgxunzgNovMulXh3ZCRwC4K0Q3IIzuasdYKtwPHvLy
            1bKD0xPJeBzKG7vaLqF/bvBtvfTz3svzex2IXdL1yg==
            =X3zh
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts)$
    version: 3.7.1
