---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: memos
    namespace: memos
spec:
    interval: 15m
    releaseName: memos
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: .
            sourceRef:
                kind: GitRepository
                name: memos
                namespace: flux-system
            interval: 10m
            version: '0.1.0'
    #TODO: add option to disable metrics:
    # https://www.usememos.com/docs/advanced-settings/metrics
    values:
      replicaCount: 1
      image:
        repo: docker.io
        imageName: neosmemo/memos
        tag: stable
      persistence:
        enabled: true
        existPersistClaim: memos
      ingress:
        enabled: false
      #podSecurityContext:
      #  fsGroup: 2000
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        #runAsNonRoot: true
        #runAsUser: 1000
        #runAsGroup: 1000
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
...
