apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: memos
  name: memos
  namespace: memos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc
  volumeMode: Filesystem
