apiVersion: v1
kind: Secret
metadata:
    name: authentik.authentik-authentik.credentials.postgresql.acid.zalan.do
    namespace: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:HoKDF1ffEb0h,iv:qX6zQXj7xSd8RFfixG5rpegdGSHt71Yrq9HxRq7BIgs=,tag:LMOgZnCGiwZhFiuJz8/GKA==,type:str]
    password: ENC[AES256_GCM,data:cWpABeGq912kMVyL2F1DkSxnlQdcey2aLdqLzwkxhrTZSaP3JPYEvs/0ZIg=,iv:GGPyY4O2/DD2I9VWnvEDYMA/sAuk8F8of31Q65RGhBM=,tag:lvXFySD6EN2HQoZAit1yTw==,type:str]
sops:
    lastmodified: "2026-08-03T13:27:41Z"
    mac: ENC[AES256_GCM,data:Ug3JEoZtGOgKpYnA4VyI/7UXFbQIpV7umL9xk0BHiZmtM29wMtfbTaJz1BsmPYmT3FwpIFxZqj1QczGpNRPO0eN18sqeszT5/73A4Glo3PTNbqhEt5FT0GUFEAndDBiE7ayigaF+lktAEDUxvR0KdJOiZ836IddnLO1CBzM9NSU=,iv:XBqccJkKiDK8gpxBLjqtzI0Q5wi7QSC4U6gGQEdO8E8=,tag:t65C0+xT24vRwZ5vL0kEKw==,type:str]
    pgp:
        - created_at: "2026-08-03T13:27:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+Nyq5V0+GIBe0ZfHyjLqmHIE+i1iZXlO3NvexEtK47aze
            SQ4V49Q/tg8bXgPHMVcbtrhnRMc75o6nZxKKpzS/utTug/VNEr9rppREDQqpcsWN
            2O/1vzlX/x2KMIoJjzwZzR/kkskp53rf0sQ2MA/cSYmRuP/Py4MVYpHdZv4qOkqZ
            kN6f156gddwDLca+x9+Zp3eragE4OEOvsWcWB8DosXgeGYRiRw/ZQFUw/6nr2r0F
            Ccz1yHLmu48Twq8xw5Gh4irBkghLbjfLzH/IO+Tf6abB9ksrEHGqp42i8cfJ0G0G
            eS01QoWJlzm2lBC1Cs+1R2hil+MmZbaCeHGQK1T4gcQYFpjDu3C0nspUolmXy88O
            vgqMvZqBi8Hu7Ci7aD5ZUZFL44ikYkvsjaSEwO1Zwb8ubax6ow6h+hJOLYkzT4gD
            ROYAEzsRQP2l58EBkiifGGqdXLBW4Ad06AQ8PhcLX8Kl3RYzJFir3ycwueWU8euG
            dCwfktgKUuBFpJPVOe5PeU4FwUeozxzhF23nzREIBzVRKJLSSCC5sw4Mjv9Dy5gZ
            uWOkDdmPAiZcre42QPcltg2GuqQnhx1n7WGenpT1tasqJpW2rLtcWY04kOpMrbA5
            qIZ5nYoPiHq/+iJW8Qk+0rWOAvl07tVqamrEh0Cb0qvSNXKhygPSVwumG9Pao8PS
            VgGy9gpcYZaAPymfgvOKPzJS/pQbvMa+ByC2w5c0NYj4tjiGMmY85QlO7oQQgtPc
            yl7qFt2dSvz4STgcynVZkVoU+PJ2w7AypapV/rAvE9vSbsRxXJ94
            =6Ox7
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
