apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
    labels:
        apps.gitops: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:x1jts7VcMPygCHVqf2aTFN+CWO1t6rqp6dEUxp3uZiEA01Q6EIJ54WAeG43pHsndtQkF9sYkrvjDYniZEkm1pFNAEBSKMWEFbnPVsMKslZdgMhHm5lpbIA==,iv:4rjlvH5SDdwNpCtWCPjnHFuRmaw5y7cglxFoJFK6vNA=,tag:WO+X1t7mAwh0dPtVYh4HGQ==,type:str]
    #ENC[AES256_GCM,data:Eqm8I2gAJaHyG8txSJlJxf6owqVHJpU9N7kH4mJTA/dY8TRFWs6xxx8UhdstSmq8YH2VhYdXzdb7ANtfuis=,iv:bFrLyirg6xg52QWKpfKK69duIv+gADFV9gzkoUujHbQ=,tag:yvCO8jNhxJKanwHBmpmhiQ==,type:comment]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:0rcSxqXwQ55AKgOcZhWM7VXsUzV+SDsIrgxsrwFNkg0TsqyfvnckuSJalX4=,iv:JiZzRfw/LGZClkh5OTZWhOjifnQpWAaxy2XGIDw8p/A=,tag:i8go8MfEHNQVeipu0FpEpw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:wuVUvXC5qmdq/p9NmbX0A0OSugsSU43wAnAS0gLJvmk=,iv:9O3M9rGW6aoXvzcw87I4L/Jy+7QsLdXT1ZUrbDin+1s=,tag:X1f5XB/NAvqOVsfgzQufVg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:t86vFAxwFK4ojWAUVzShnnhB6nOeOVVPCOio4Pe4LVlSrmCUj0e9Q0X8TAE=,iv:HZ3IOtkrAz/OTv/+Qm8eE/wL8U1oF9jCuVdvWcx2NeU=,tag:bs8myWDNTn66bg4s7yJuBg==,type:str]
    #ENC[AES256_GCM,data:302i1hF4Y2bYH+Fe+NPVpRdbK6gO/fjlSivAA7wC+GjuyiCX/Ht1Y4swZKNjylt9/UX7yIWdpIZnMI6cM1OM3RIiUzTdBy6UO8l5ag3RvQ==,iv:z0/KF2H8/MOIBNSvOBrpiibGXw3iJFEaxiL34DUajU0=,tag:/l1KFuOhInkk5F+0R1vSwg==,type:comment]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:9Qk+ku40Js1Bo/yLlrOgda7nvm1/520r6cE5U949DFbEu+Tk3GCHH7ksd8W/qL8=,iv:iCZBVo7t27oqxBboJuB5xRGdPcKAjTdR+YXprpxajcg=,tag:jBESpa/BKnViGDKWyeTUCQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:lrppuIdzvoJW,iv:k67ek3cTynKwBnIek7Q8GWMo9vJu6wVMcTq8wT4WFhI=,tag:RH8aVyXG4EG9dEND309ZVg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:ssAL61g8VFKa,iv:2RCVgj3SHBGfP7VyWk4qmKaKZqKPRse9t/CAdYzLtI8=,tag:1UUjaJkii7RRoatQ637X9A==,type:str]
    #ENC[AES256_GCM,data:k9qNSl+qd0mvGaAyxmd0QGvej5kPod1I2QUXF7/BRq4=,iv:o1EhkHsLV+3kSRuIj209PFs47GNieefnmmHL3HtRTkk=,tag:0atcPSqsgKNVxfFfylYIQA==,type:comment]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:spb7dXagTe3xh+Evk1AkER1ALFo=,iv:S8/O/xC1MvvWSdufnsaumWUCXuyT0/5ABoVWWhHM2p8=,tag:ejaY1J+jWrSe50HZQu3o2Q==,type:str]
    AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:hpZgnT2B0w==,iv:3KYgvW2CzN1KGosN1KlpPvgpHaXzfbjRuEHk6wR2/8Y=,tag:1KjcM+18QB6L9ArNt1xWqw==,type:str]
sops:
    lastmodified: "2026-08-03T13:27:47Z"
    mac: ENC[AES256_GCM,data:Jf2xJ7j/k8H/TCJXKnkc22SxNpr2XW47gQ6Vaq/SBmKAHJSRYSI/7nuqmZsxtAHw1KbNlkp2oFdIfi2LqNARUIV4nLGQZlFSY3nl7w+7i7pV3am7cnOS+Hukq1xWeh5utabxkcUvivvJINrM34r+CsvTgYDuhBTxiDOty8iPgKc=,iv:n20Am56GcRODMX7L2uQZEyA3If66TlG/IUAIczAPDm4=,tag:1BO+pY/L/12F0g5K1DXQ+A==,type:str]
    pgp:
        - created_at: "2026-08-03T13:27:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//Yji4tPFsrEeGVIzJ0Dx03t/TFXa7RWKVLIA/OugVGvM6
            vh00yKcvHa7d9OnAwFQUchLAZeX/QxSktzXiDV0a4XO6rb6hJRP9numeopAtfZfa
            gDSS/li9arWGx0+65GhRQIi5ygpXEFj0UCX4jGnEA0DpX3KtWt0WKZJCBvYGgrWf
            INd/hAJPjvmoYqYvVu7EfKnDoNCMFz1xfvlHRRn7O7ixjeZpzNiPZRXnyuKq20u/
            C4+xAYjuB0mBe/itzaM55iKUH2Ng4ivyuDbfxysMZVtMpaJDEIurF1/CiDQaSqcl
            Efhdzh1lzVhrW2D1Oaxr/OljsJl0jlc1lAd8D9kEFYpIsY8kOrvRYlZpAPQf9QbE
            fVNfYLiLAlUTjErzeo/BuoHez9ILmfJK7CWv3TonLZ8c7aSt+2ng+R59o1f0zB+A
            xJ3Kd83bd3R5E/sfyrwx9+rzVJH881jPrVDHCjLc9lC1yscfnx528haYjYF35Lw6
            FzZDVjyt7Qh1Wd1BNeSINVANHyS2ZB/p5qF7cLaY1ZCl9jK3tB8WVCjqvgejkyHr
            clidqbgFe3+b9gL+EsORA857BC6Tg83ff5t/6cCYRL58qcppovTcEW1IlQ37esMf
            hvzFIJXXGp2WOTXqf+i5pGJFNiE+yHRraZMblVbiXd5FGft1XQu/ck/99kY5i5bS
            WAGTzSuoL/6UgTrlNJV4V47ehFywivS3zIW3npcidHE0djhCdDvIoP/p0eTX/7Ng
            ljF3sgz4CMPdaCzdw6wt/KK57zYlqFi6qd0f6dh2VpA+oH6jSQSqoPA=
            =ei2y
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
