apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-authentik-source.yaml
- authentik-pg-secret.yaml
- authentik-pg.yaml
- authentik-blueprints-secret.yaml
- authentik-secret.yaml
- helm-authentik-release.yaml
- authentik-ingress.yaml
