apiVersion: v1
kind: Secret
metadata:
    name: brokenpip3-jenkins-pull-secret
    namespace: jenkins
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MU/ECCyRNWqycJktAddb0wxfIkXkSXhM/203kZbiSqb7fJ0QBeMe8fXDiuKeJODiw8qtpJvWx5rBr5CfGN9Gm5oAj/Fdx3vD5FTV13Cav3ZButYej7hGpLvO4sPDax20Zo62RGspPZ4VofsfCdhcnOz6u601ZIQ2wzdD605OZ2hoiWciMcjNnfDInUVsYXAjuH9Fu2iAgHZS4WnRz7NTNLKdy/RwXJsPocO+js9TDxOZ7Ehybp9AAFe1D0b6YlAb1gjDNgxa3moKYXdrXLLjWcYszaWEIcV4zgA2nbrML6Ig8aDtOlgxUKnrvVWUrK3RkpRQZpabYtnnU7GOrKIS2g==,iv:BoiUAHDOGjwR+w4XPVbckqXuyUg8P1/lyeJ+0dvryrw=,tag:pceFr4YN8O8u/jhYut2q5g==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-21T21:15:05Z"
    mac: ENC[AES256_GCM,data:5VTBf1nsRn1WDkosruew1BiwJ6OzCO3UpnWSXCJyv0fr/CoHIHqPGqBiZ4nK5aAyYDtOqO89ZH9/uFSFImOUpoQfQI+d6dXtR9rXUY7lnSZxMdB+BM2aPAAHCwA1RAOfTGNFvORnJm7CTqbn64MuJNs/VR3mR31e0lilnivWMsw=,iv:1z1cP44GwsrCF0IpBnRgBuOsfdBhsSKP4UROBo+i5Hk=,tag:X1XX1C7/NHUXjbH6EZONpQ==,type:str]
    pgp:
        - created_at: "2021-10-21T21:15:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//UQ1ll0TPSUC2mBPTRWIqB3Y9CaAHvzj8OeNnGIVJFlWb
            U3uxREd8QLicxAv/PS0oG0X3hqZQJHz9H/cIgKsXBgSXvaalD9Vo+M9Ar5LOxvsN
            0eVW5pDU4cSdTfyINB3IbVP7kNbREeqfMru7lxAxARn4grS3n+MacNTQnrdAgreE
            1KpPltqjQ2NHvYMPOv8F92n6o8uvjwEAbeeEDgnYcuibOwOAjGOutm0MDJkMXhqv
            +yaa1feC8dsf6Glesvpiz8CSLRaik2Xr4uAy85lY1jB4kT93g04WT863jbk9QEfw
            j78KcMXIHZYkopMTdw3iJtb9QehKeqcqk6Xfe4dWuqLCKuQtW81dGzwGqf6mpyCJ
            Qpu0V9Gqd0PhvKrHgL7rAd437t7uOHv5WPZxSi4adcegUKhVe/4DdpmQDU8Dinp2
            SotmN4qvZN3cdBlC2q0XBZFcXN7DOMaWFBsYe54EprqZYEQ9KLWOQuQyRD14fxJc
            ibaXTksA+QPHObtaitJ/R91DfPtrYUAniD5k+YkUhkpt7zmftUGB2VvMFFMiy6oj
            lP6Yz8rKglKOqINCAIDLPtrC8fJcKLSNb6tfnM6HwPM+VlnpMlYw96qxkyUrw8/N
            LbMKobCjGNo20CHE+kDS0YBOU4MEdOTqrAEV1jtl/FVTsae/xLGkjfRKpr20Al3S
            UAFK6QldmJhZnS9aMJkLqDLn46KcEUPs8DSo3meMc4KfyzvTxKT2aD17dXUgVrFa
            kqhQcfJtkGJvF98f9THPa9GeShAQOBYX+ruC/m8zQbEP
            =fTfN
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server)$
    version: 3.7.1
