apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-ovh
        kubernetes.io/ingress.class: nginx
    labels:
        app: ublock-list
    name: ublock-list-ingress
    namespace: ublock-list
spec:
    rules:
        - host: ENC[AES256_GCM,data:Ihpgli7Q7KhEtyObTlOI5/0K2FJaFqcnIpDV4Q==,iv:PzOOh7uf46krcCSNx2tpe8sweA5D++Hb1bIPEkaJx5A=,tag:NuiCpubxciNXMRlG/5Hiog==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: ublock-list
                        port:
                            number: 8080
                  path: /
                  pathType: Prefix
    tls:
        - hosts:
            - ENC[AES256_GCM,data:WvVo9VmhdElCl3bSvXMB5dY6E3iCu2z/RwbXqQ==,iv:9ZtL8pTgPT5V4lZw/Jk0kLAbOeRQbyFkn/FfXr20eXE=,tag:dzJ4I6HJr0dyXuf2B/kEUg==,type:str]
          secretName: ublocklist-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-09T15:22:43Z"
    mac: ENC[AES256_GCM,data:K1hqhzxGpBSl0JL5vOJK7+4xlpPT6aLwpUCz16Z2gkSnynC+T8IlWRpF6MHajG1cGONo9BwzSyw3Nynmhhc+bJUl5a81kZ/Dws9pAp4v7OAPnBRI9Z/JLD6DWwbTVxoy7KnpgeaBkMKA4OWAfIS3gk31P2igFg+i3tpwsMtBvFI=,iv:RBxcd/PsvVv1aa/XvMh26sBdcgm5x7k4lEDEg6hxMek=,tag:6GQv5qsa4uMRHAbgeRgTBw==,type:str]
    pgp:
        - created_at: "2022-01-09T14:39:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//dOdT355l1KpKp+UBYfTwcb9xijQulthJvQypr8aQFQAb
            TIy6E3uSBKP74U2ehz7N/Ep/DXvVHRjXIt/QCuYHn+qggyLDqqEXRh4/BvU07ksW
            VP5HoSWbilcaGQRbWytUkpsZodYKCtZvO9XzDL89vGHKtLFwOyzmu+QCoeZmOtM6
            RDjByhqqIHFhFVxP2zcIQa/teaTeYJDqMdRfzT/Y48HIwC+IUittqiJmu52HPoWO
            vCI9gtOW2l7QQC0t704eDY4i7veQsoY+jlao/9wkwl4kHe4ZahmRJw6ntplC2Coq
            yCjvN8X+xFDvQbdMfQbGYc2QSFOOgXNwslIiWH916cGorKYAPNYWjTTrG+PL6BlH
            ewxP67DnuOnygrIZtekIV91AA+XifpjYhPRJ86cMWxp4h3kovwO8NJ0As+55H5gY
            Vk9W8jC9e0ydNq+klWb5UquQ+MyGJQ1yYtQ6OOxp/HodV5heIL5/Gt2Ody1Zddv4
            GZvtt/T282shF1B4h6CSU+ttasURiWEHVGnCjAsRRf+lzU38cyn5nSuWBW7MQrOn
            A7S58F9t1tJG7okh78LWtqL7KrA9A/6Rp6hEiOUPpFZ3K8XthPe1FCJuQeDK5N9i
            ssaKTgBoEKl5EZzHwMAlfgAnDakn6dTb+HTzyIOek28Xpe+AFEWnqgZyx7cktW/S
            UAEnwjamKIfzBKHKyTWSvE4YyDlyjRWz6LaECSwLICaA17CaR5KVIym8VTX1OHr9
            69SOrtGny2mPkzsC1SkbSgqClkgz8fHyU7R3swZ8R59k
            =xWaU
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
