---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: cert-manager-ovh
    namespace: flux-system
spec:
    interval: 10m
    url: https://github.com/baarde/cert-manager-webhook-ovh
    ref:
        tag: 0.3.1
    ignore: |
        /*
        !/deploy/cert-manager-webhook-ovh/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager-ovh
    namespace: cert-manager
spec:
    interval: 10m
    releaseName: cert-manager-ovh
    dependsOn:
    - name: cert-manager
    chart:
        spec:
            chart: deploy/cert-manager-webhook-ovh/
            sourceRef:
                kind: GitRepository
                name: cert-manager-ovh
                namespace: flux-system
            interval: 10m
    values:
        groupName: acme.k8s.brokenpip3.com
        image:
          repository: quay.io/brokenpip3/cert-manager-webhook-ovh
          tag: 0.3.1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh:secret-reader
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ovh-credentials"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-ovh:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-ovh:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-ovh-cert-manager-webhook-ovh
  namespace: cert-manager
...
