apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-ovh
    namespace: cert-manager
spec:
    acme:
        email: ENC[AES256_GCM,data:IaHj7d+2l5C1lEjaQyptfgq2CnA=,iv:WydZwz/XAH3szmasSPQKdt9Ecr5a32o1sZQvO2o+86k=,tag:BSfJbjZFQNkfxfhuGsP82A==,type:str]
        preferredChain: ""
        privateKeySecretRef:
            name: letsencrypt-ovh-account-key
        server: ENC[AES256_GCM,data:i67ssUTvQ5d8vI85/5Zt6S/a6ksTsj/gqFqByBfZeGkjogjmmtHi9TLbMw8CQg==,iv:xpzw5htjuq71idkkAFnkR06LsejJn4Ld3L8TTkpZLI0=,tag:rUPBhXnGq0m4tWe/aoQDdg==,type:str]
        solvers:
            - dns01:
                webhook:
                    config:
                        applicationKey: ENC[AES256_GCM,data:0A17sI6Lq2viilI2S22K2A==,iv:Ld2EfsDsIH5jzu1LiO/ZXniBe8mIvtWz2LfnX1XQyCs=,tag:Z0odDCVRnMZ4OLKXKgnicw==,type:str]
                        applicationSecretRef:
                            key: applicationSecret
                            name: ovh-credentials
                        consumerKey: ENC[AES256_GCM,data:2H3BKVoFk9lqokeANk9JUoTlzbUon6iBTOYZqGaq4dE=,iv:2+PTC9xRb6rK0VchUTr3wRPlks5UObwvHTeA8sjNB0o=,tag:tTIoYBHtZ4QvUyZn0lhCRA==,type:str]
                        endpoint: ovh-eu
                    groupName: ENC[AES256_GCM,data:nDX8emM/4wltJZuaCbAi7y7G+xIKLpA=,iv:0y6qB1ewGPOI+KWCVU3eOIwWIE10MxBJUITxsBildEE=,tag:RTHsxvmXQu9wt8LfDLBpWg==,type:str]
                    solverName: ovh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-31T16:55:18Z"
    mac: ENC[AES256_GCM,data:SjWAiiwn3RmKm44Y79y9+hQnVevZ5JkonxIdOIXYvVaSHiyetCZGXmle1aOAmaBWwG6H1n3kJG5/jYUxAEuViVC9fQpElBT2OBcojVFmQTHUlIAyQrnfZbfOJFbaKKQsVJfblBB1tutLqwEzmWuYwOxOwsUWCOtyUBgGLlpXy4w=,iv:0VssTraubt6ybToWkyYeKMhyND9iepH/9ZS1/8U4Hs0=,tag:lTvwNfU+t1DsPoswVox/2A==,type:str]
    pgp:
        - created_at: "2025-12-31T16:55:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+IYyVkNHw/7Ea/+bsplwNPSoZzSvO5TFn5FzboUWcWEEL
            MpceuaNWUzBkYZfyyY5Miy1/c7w/aFH7NjVUWBM/LK7G2Q+A4adJz6FB/xyMoij4
            rZ5ZB9drAJHYZnllQXiJ6XEk3VPAAM85fqa2fmWuH/IFolmGSbS5HzLNlOBSIJFw
            p0+vDAVR41MnSQP4uAytTUwQKXEkbUWLrD9yKcjtmq9dllnqWw5Cn9Uk7J2N87sT
            BAjdXSHCCmaql5ERhTtsxcV17anmkqB5S17duoFx+VbomVUJUPxAJ/mtmw3gvheg
            +WcILb+kTGWF6ajd5nhg/xCwkPs0rY0OpjMB70dJXNuwCBds11wz+MwuAnd7sXSa
            Rewgaguv0Fug6/SXhO5mUZf7YJa6WKlKPGCpVQrTaml7CC1xOhSdqJB9S08DGucf
            islkD3J2tE358jxgojdE7kFqnbu/wdQkpVO4a5+Yyeix1LUUeir7btMyNELTTlTa
            A9j9SK8epQopQu+FVHo3071bXaUHULgYInGodPjLDpVve+rW2BaJfAoUreZxNNi8
            rbZlzXDwEKY8rsIgzXQG1zYIYejxWTR7etKli5Uo7mXfQGwTshqgQvwCO8kZWa39
            b29jbJjhFDSWzn5MrIHUunIBY7DflOC86byyJIp60XHmA6Avw49iUwK9WLJt02bS
            VgFgkhepX8JwdH0pjdr3d9NDhMxSUAr9JziVWo1IBLWf34wL60R9Y3NFimK9i3tf
            JfYz9IZbjIUDtufCbqR8ewARJsZeF6JYKUUztWUBvT8rIEkfQrr8
            =djS1
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    applicationSecret: ENC[AES256_GCM,data:QMmIjv9o935rtjTkOEJF3tkthLOSf5QEMyLP5PF4AkE=,iv:axzNr7tgTOpf5Ww8FdVW62db9h6pko5Llg5WazpFUVw=,tag:f+F/T4scPyvccYOiCXwQEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-31T16:55:18Z"
    mac: ENC[AES256_GCM,data:SjWAiiwn3RmKm44Y79y9+hQnVevZ5JkonxIdOIXYvVaSHiyetCZGXmle1aOAmaBWwG6H1n3kJG5/jYUxAEuViVC9fQpElBT2OBcojVFmQTHUlIAyQrnfZbfOJFbaKKQsVJfblBB1tutLqwEzmWuYwOxOwsUWCOtyUBgGLlpXy4w=,iv:0VssTraubt6ybToWkyYeKMhyND9iepH/9ZS1/8U4Hs0=,tag:lTvwNfU+t1DsPoswVox/2A==,type:str]
    pgp:
        - created_at: "2025-12-31T16:55:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+IYyVkNHw/7Ea/+bsplwNPSoZzSvO5TFn5FzboUWcWEEL
            MpceuaNWUzBkYZfyyY5Miy1/c7w/aFH7NjVUWBM/LK7G2Q+A4adJz6FB/xyMoij4
            rZ5ZB9drAJHYZnllQXiJ6XEk3VPAAM85fqa2fmWuH/IFolmGSbS5HzLNlOBSIJFw
            p0+vDAVR41MnSQP4uAytTUwQKXEkbUWLrD9yKcjtmq9dllnqWw5Cn9Uk7J2N87sT
            BAjdXSHCCmaql5ERhTtsxcV17anmkqB5S17duoFx+VbomVUJUPxAJ/mtmw3gvheg
            +WcILb+kTGWF6ajd5nhg/xCwkPs0rY0OpjMB70dJXNuwCBds11wz+MwuAnd7sXSa
            Rewgaguv0Fug6/SXhO5mUZf7YJa6WKlKPGCpVQrTaml7CC1xOhSdqJB9S08DGucf
            islkD3J2tE358jxgojdE7kFqnbu/wdQkpVO4a5+Yyeix1LUUeir7btMyNELTTlTa
            A9j9SK8epQopQu+FVHo3071bXaUHULgYInGodPjLDpVve+rW2BaJfAoUreZxNNi8
            rbZlzXDwEKY8rsIgzXQG1zYIYejxWTR7etKli5Uo7mXfQGwTshqgQvwCO8kZWa39
            b29jbJjhFDSWzn5MrIHUunIBY7DflOC86byyJIp60XHmA6Avw49iUwK9WLJt02bS
            VgFgkhepX8JwdH0pjdr3d9NDhMxSUAr9JziVWo1IBLWf34wL60R9Y3NFimK9i3tf
            JfYz9IZbjIUDtufCbqR8ewARJsZeF6JYKUUztWUBvT8rIEkfQrr8
            =djS1
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths)$
    version: 3.9.0
