apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      version: v1
      kind: Namespace
      name: flux-system
    patch: |-
      - op: add
        path: /metadata/labels/prometheus
        value: scrape
