---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: /chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
    values:
      operator:
        replicaCount: 1
      jenkins:
        enabled: true
        namespace: jenkins
        image: jenkins/jenkins:lts
        plugins:
        - name: github-branch-source
          version: 2.11.3
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.39"
        - name: view-job-filters
          version: "2.3"
        - name: prometheus
          version: "2.0.10"
        - name: metrics
          version: "4.0.2.8"
        - name: ansicolor
          version: "1.0.1"
        - name: "sidebar-link"
          version: "1.12.1"
        basePlugins:
        - name: kubernetes
          version: "1.31.1"
        - name: workflow-job
          version: "1145.v7f2433caa07f"
        - name: workflow-aggregator
          version: "2.6"
        - name: git
          version: "4.10.1"
        - name: job-dsl
          version: "1.77"
        - name: configuration-as-code
          version: "1.55"
        - name: kubernetes-credentials-provider
          version: "0.20"
        backup:
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 5500Mi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: '10 */1 * * *'
...
