---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.9.0-beta1'
    values:
      operator:
        replicaCount: 1
        image: quay.io/jenkins-kubernetes-operator/operator:v0.9.0-beta1
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.516.1
        plugins:
        - name: github-branch-source
          version: 1809.v088b_5f22c768
        - name: github
          version: 1.40.0
        - name: pipeline-stage-view
          version: "2.34"
        - name: build-name-setter
          version: 2.4.3
        - name: ws-cleanup
          version: "0.47"
        - name: view-job-filters
          version: 392.v2c0a_4dd46909
        - name: prometheus
          version: 819.v50953a_c560dd
        - name: ansicolor
          version: 1.0.5
        - name: sidebar-link
          version: 2.4.1
        - name: command-launcher
          version: 115.vd8b_301cc15d0
        - name: cloudbees-disk-usage-simple
          version: 205.v47f4ee8803d1
        - name: throttle-concurrents
          version: "2.14"
        basePlugins:
        - name: kubernetes
          version: 4324.vfec199a_33512
        - name: workflow-aggregator
          version: 608.v67378e9d3db_1
        - name: workflow-job
          version: 1505.vea_4b_20a_4a_495
        - name: git
          version: 5.5.2
        - name: job-dsl
          version: "1.91"
        - name: configuration-as-code
          version: 1950.v506f96a_69516
        - name: kubernetes-credentials-provider
          version: 1.276.v99a_de03cb_076
        backup:
          image: quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.3
          enabled: true
          pvc:
            enabled: true
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 * * * *"
...
