---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.8.1'
    values:
      operator:
        replicaCount: 1
        image: quay.io/jenkins-kubernetes-operator/operator:v0.8.1
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.462.1
        plugins:
        - name: github-branch-source
          version: 1797.v86fdb_4d57d43
        - name: pipeline-stage-view
          version: "2.34"
        - name: build-name-setter
          version: 2.4.3
        - name: ws-cleanup
          version: "0.46"
        - name: view-job-filters
          version: 382.vdf2d5e3f02f0
        - name: prometheus
          version: 784.vea_eca_f6592eb_
        - name: ansicolor
          version: 1.0.4
        - name: sidebar-link
          version: 2.4.1
        - name: command-launcher
          version: 115.vd8b_301cc15d0
        - name: cloudbees-disk-usage-simple
          version: 203.v3f46a_7462b_1a_
        - name: throttle-concurrents
          version: "2.14"
        basePlugins:
        - name: kubernetes
          version: 4285.v50ed5f624918
        - name: workflow-job
          version: 1436.vfa_244484591f
        - name: workflow-aggregator
          version: 600.vb_57cdd26fdd7
        - name: git
          version: 5.4.1
        - name: job-dsl
          version: "1.88"
        - name: configuration-as-code
          version: 1850.va_a_8c31d3158b_
        - name: kubernetes-credentials-provider
          version: 1.262.v2670ef7ea_0c5
        backup:
          image: quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.1
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 * * * *"
...
