---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.8.0-beta'
    values:
      operator:
        replicaCount: 1
        image: quay.io/jenkins-kubernetes-operator/operator:v0.8.0-beta
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.387.2
        plugins:
        - name: github-branch-source
          version: 1703.vd5a_2b_29c6cdc
        - name: pipeline-stage-view
          version: "2.32"
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.45"
        - name: view-job-filters
          version: 364.v48a_33389553d
        - name: prometheus
          version: 2.2.2
        - name: ansicolor
          version: 1.0.2
        - name: sidebar-link
          version: 2.2.1
        - name: command-launcher
          version: 100.v2f6722292ee8
        - name: jdk-tool
          version: 66.vd8fa_64ee91b_d
        - name: cloudbees-disk-usage-simple
          version: 178.v1a_4d2f6359a_8
        - name: throttle-concurrents
          version: "2.13"
        basePlugins:
        - name: kubernetes
          version: 3923.v294a_d4250b_91
        - name: workflow-job
          version: 1292.v27d8cc3e2602
        - name: workflow-aggregator
          version: 596.v8c21c963d92d
        - name: git
          version: 5.0.1
        - name: job-dsl
          version: "1.83"
        - name: configuration-as-code
          version: 1625.v27444588cc3d
        - name: kubernetes-credentials-provider
          version: 1.211.vc236a_f5a_2f3c
        backup:
          image: quay.io/brokenpip3/jenkins-kubernetes-operator-backup-pvc:v0.2.1
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 * * * *"
...
