---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 10m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    chart:
        spec:
            chart: /chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
    values:
      operator:
        replicaCount: 0
      jenkins:
        enabled: true
        namespace: jenkins
        image: jenkins/jenkins:lts
        plugins:
        - name: github-branch-source
          version: 2.11.2
        basePlugins:
        - name: kubernetes
          version: 1.30.1
        - name: workflow-job
          version: "2.41"
        - name: workflow-aggregator
          version: "2.6"
        - name: git
          version: 4.8.2
        - name: job-dsl
          version: "1.77"
        - name: configuration-as-code
          version: "1.52"
        - name: kubernetes-credentials-provider
          version: "0.20"
        backup:
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 5Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: testing-job
            targets: "jobs/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/jenkins-iac-seed-jobs
...
