---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.6.2'
    values:
      operator:
        replicaCount: 1
        image: docker.io/virtuslab/jenkins-operator:v0.7.1
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.332.3
        plugins:
        - name: github-branch-source
          version: 1656.v77eddb_b_e95df
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.42"
        - name: view-job-filters
          version: "2.3"
        - name: prometheus
          version: 2.0.11
        - name: metrics
          version: 4.1.6.2
        - name: ansicolor
          version: 1.0.1
        - name: sidebar-link
          version: 1.12.1
        - name: display-url-api
          version: 2.3.6
        - name: junit
          version: 1119.1121.vc43d0fc45561
        - name: pipeline-model-definition
          version: 2.2097.v33db_b_de764b_e
        - name: pipeline-model-extensions
          version: 2.2097.v33db_b_de764b_e
        - name: pipeline-model-api
          version: 2.2097.v33db_b_de764b_e
        - name: pipeline-stage-tags-metadata
          version: 2.2097.v33db_b_de764b_e
        - name: workflow-basic-steps
          version: 969.vc4ec3e4854b_f
        - name: workflow-cps
          version: 2746.v0da_83a_332669
        - name: workflow-support
          version: 833.va_1c71061486b
        - name: workflow-api
          version: 1188.v0016b_4f29881
        - name: workflow-durable-task-step
          value: 1174.v73a_9a_17edce0
        - name: script-security
          version: 1175.v4b_d517d6db_f0
        - name: command-launcher
          version: 84.v4a_97f2027398
        - name: ssh-credentials
          version: 291.v8211e4f8efb_c
        - name: jdk-tool
          version: "1.5"
        - name: cloudbees-disk-usage-simple
          version: "0.10"
        basePlugins:
        - name: kubernetes
          version: 3663.v1c1e0ec5b_650
        - name: workflow-job
          version: 1226.v44f718dcfe1f
        - name: workflow-aggregator
          version: 590.v6a_d052e5a_a_b_5
        - name: git
          version: 4.11.3
        - name: job-dsl
          version: "1.77"
        - name: configuration-as-code
          version: 1466.v2d4119502006
        - name: kubernetes-credentials-provider
          version: "0.21"
        backup:
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobAgentImage: docker.io/jenkins/inbound-agent:4.9-1
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 10 * * 1"
...
