---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator 
    namespace: jenkins
spec:
    interval: 10m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager 
    chart:
        spec:
            chart: /chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator 
                namespace: flux-system
            interval: 10m
    values:
      jenkins:
        enabled: true
        namespace: jenkins
        image: jenkins/jenkins:lts
        plugins:
        - name: github-branch-source
          version: 2.11.2
        backup:
          pvc:
            enabled: true
            className: nfs-sc 
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
...
