---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.6.x'
    values:
      operator:
        replicaCount: 1
        image: virtuslab/jenkins-operator:13f871b
      jenkins:
        enabled: true
        namespace: jenkins
        image: jenkins/jenkins:lts
        plugins:
        - name: github-branch-source
          version: 1628.vb_2f51293cb_78
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.42"
        - name: view-job-filters
          version: "2.3"
        - name: prometheus
          version: 2.0.11
        - name: metrics
          version: 4.1.6.2
        - name: ansicolor
          version: 1.0.1
        - name: sidebar-link
          version: 1.12.1
        - name: display-url-api
          version: 2.3.6
        - name: junit
          version: "1.63"
        - name: workflow-basic-steps
          version: 948.v2c72a_091b_b_68
        - name: pipeline-model-definition
          version: 2.2081.v3919681ffc1e
        - name: pipeline-model-extensions
          version: 2.2081.v3919681ffc1e
        - name: workflow-cps
          version: 2692.v76b_089ccd026
        - name: pipeline-model-api
          version: 2.2081.v3919681ffc1e
        - name: pipeline-stage-tags-metadata
          version: 2.2081.v3919681ffc1e
        - name: workflow-support
          version: 820.vd1a_6cc65ef33
        - name: script-security
          version: 1172.v35f6a_0b_8207e
        - name: command-launcher
          version: 81.v9c2cb_cb_db_392
        - name: jdk-tool
          version: "1.5"
        - name: cloudbees-disk-usage-simple
          version: "0.10"
        basePlugins:
        - name: kubernetes
          version: 3580.v78271e5631dc
        - name: workflow-job
          version: 1181.va_25d15548158
        - name: workflow-aggregator
          version: 578.vf9a_f99755f4a_
        - name: git
          version: 4.11.3
        - name: job-dsl
          version: "1.77"
        - name: configuration-as-code
          version: 1429.v09b_044a_c93de
        - name: kubernetes-credentials-provider
          version: "0.20"
        backup:
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 10 * * 1"
...
