---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.9.0-beta2'
    values:
      operator:
        replicaCount: 1
        image: quay.io/jenkins-kubernetes-operator/operator:ce17cbd
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.541.2-lts
        plugins:
        - name: github-branch-source
          version: 1967.vdea_d580c1a_b_a_
        - name: github
          version: 1.46.0
        - name: pipeline-stage-view
          version: "2.39"
        - name: build-name-setter
          version: 2.5.1
        - name: ws-cleanup
          version: "0.49"
        - name: view-job-filters
          version: 406.va_0ec67147ee2
        - name: prometheus
          version: 852.v317db_5d17a_b_0
        - name: ansicolor
          version: 536.v13fa_b_860c267
        - name: sidebar-link
          version: 2.5.0
        - name: command-launcher
          version: 123.v37cfdc92ef67
        - name: cloudbees-disk-usage-simple
          version: 256.v20ec4eb_884f1
        - name: throttle-concurrents
          version: 625.vc8b_e469e9a_b_c
        basePlugins:
        - name: kubernetes
          version: 4423.vb_59f230b_ce53
        - name: workflow-aggregator
          version: 608.v67378e9d3db_1
        - name: workflow-job
          version: 1571.vb_423c255d6d9
        - name: git
          version: 5.10.0
        - name: job-dsl
          version: 3654.vdf58f53e2d15
        - name: configuration-as-code
          version: 2037.v8e5349845172
        - name: kubernetes-credentials-provider
          version: 1.303.vdfcf47fb_b_fef
        backup:
          image: quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.4
          enabled: true
          pvc:
            enabled: true
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            memory: 6Gi
          requests:
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 * * * *"
...
