---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.6.2'
    values:
      operator:
        replicaCount: 1
        image: virtuslab/jenkins-operator:60b8ee5
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:lts
        plugins:
        - name: github-branch-source
          version: 1701.v00cc8184df93
        - name: pipeline-stage-view
          version: "2.28"
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.44"
        - name: view-job-filters
          version: "2.3"
        - name: prometheus
          version: 2.1.1
        - name: ansicolor
          version: 1.0.2
        - name: bootstrap5-api
          version: 5.2.0-3
        - name: sidebar-link
          version: 2.2.1
        - name: command-launcher
          version: 90.v669d7ccb_7c31
        - name: sshd
          version: 3.275.v9e17c10f2571
        - name: jdk-tool
          version: 63.v62d2fd4b_4793
        - name: cloudbees-disk-usage-simple
          version: 178.v1a_4d2f6359a_8
        - name: throttle-concurrents
          version: "2.10"
        basePlugins:
        - name: kubernetes
          version: 3834.vdc85747145e6
        - name: workflow-job
          version: 1268.v6eb_e2ee1a_85a
        - name: workflow-aggregator
          version: 590.v6a_d052e5a_a_b_5
        - name: git
          version: 5.0.0
        - name: job-dsl
          version: "1.81"
        - name: configuration-as-code
          version: 1569.vb_72405b_80249
        - name: kubernetes-credentials-provider
          version: 1.208.v128ee9800c04
        backup:
          image: quay.io/brokenpip3/jenkins-kubernetes-operator-backup-pvc:v0.2.1
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 * * * *"
...
