---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins-k8s-operator
    namespace: jenkins
spec:
    interval: 15m
    releaseName: jenkins
    dependsOn:
    - name: cert-manager
      namespace: cert-manager
    upgrade:
      crds: CreateReplace
    install:
      crds: CreateReplace
    chart:
        spec:
            chart: chart/jenkins-operator
            sourceRef:
                kind: GitRepository
                name: jenkins-k8s-operator
                namespace: flux-system
            interval: 10m
            version: '0.6.2'
    values:
      operator:
        replicaCount: 1
        image: docker.io/virtuslab/jenkins-operator:bef796a
      jenkins:
        enabled: true
        namespace: jenkins
        image: docker.io/jenkins/jenkins:2.346.3
        plugins:
        - name: github-branch-source
          version: 1695.v88de84e9f6b_9
        - name: pipeline-stage-view
          version: "2.24"
        - name: build-name-setter
          version: 2.2.0
        - name: ws-cleanup
          version: "0.43"
        - name: view-job-filters
          version: "2.3"
        - name: prometheus
          version: 2.0.11
        - name: metrics
          version: 4.2.10-389.v93143621b_050
        - name: ansicolor
          version: 1.0.2
        - name: bootstrap5-api
          version: 5.2.1-2
        - name: sidebar-link
          version: 1.12.1
        - name: display-url-api
          version: 2.3.6
        - name: junit
          version: 1143.v8d9a_e3355270
        - name: pipeline-model-definition
          version: 2.2114.v2654ca_721309
        - name: pipeline-model-extensions
          version: 2.2114.v2654ca_721309
        - name: pipeline-model-api
          version: 2.2114.v2654ca_721309
        - name: pipeline-stage-tags-metadata
          version: 2.2114.v2654ca_721309
        - name: workflow-basic-steps
          version: 994.vd57e3ca_46d24
        - name: workflow-cps
          version: 2801.vf82a_b_b_e3e8a_5
        - name: workflow-support
          version: 838.va_3a_087b_4055b
        - name: workflow-api
          version: 1192.v2d0deb_19d212
        - name: workflow-durable-task-step
          version: 1199.v02b_9244f8064
        - name: script-security
          version: 1183.v774b_0b_0a_a_451
        - name: command-launcher
          version: 90.v669d7ccb_7c31
        - name: ssh-credentials
          version: 305.v8f4381501156
        - name: sshd
          version: 3.242.va_db_9da_b_26a_c3
        - name: jdk-tool
          version: 55.v1b_32b_6ca_f9ca
        - name: cloudbees-disk-usage-simple
          version: "170.va_fd5b_4ee6858"
        basePlugins:
        - name: kubernetes
          version: 3706.vdfb_d599579f3
        - name: workflow-job
          version: 1207.ve6191ff089f8
        - name: workflow-aggregator
          version: 590.v6a_d052e5a_a_b_5
        - name: git
          version: 4.12.1
        - name: job-dsl
          version: "1.77"
        - name: configuration-as-code
          version: 1512.vb_79d418d5fc8
        - name: kubernetes-credentials-provider
          version: 1.196.va_55f5e31e3c2
        backup:
          enabled: true
          pvc:
            enabled: true
            className: nfs-sc
        configuration:
          configurationAsCode:
            - configMapName: jenkins-configuration
          groovyScripts:
            - configMapName: jenkins-configuration
          secretRefName: jenkins-credentials
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 60
        webhook:
          enabled: true
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 4Gi
        seedJobAgentImage: docker.io/jenkins/inbound-agent:4.9-1
        seedJobs:
          - id: seed-job
            targets: "ci-cd/jenkins-dsl/*.jenkins"
            description: "jobs-from-iac"
            repositoryBranch: main
            repositoryUrl: https://github.com/brokenpip3/my-personal-cluster-gitops
            buildPeriodically: "10 10 * * 1"
...
