apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-ovh
        labels: null
        name: jenkins
        namespace: jenkins
spec:
    rules:
        - host: ENC[AES256_GCM,data:Cefn6m3FZdimm0m/ZmBfJjoSq30viw==,iv:IMboaim6VgenPj7T00LcFPmnTCfggiBQXm18UQTZHg8=,tag:Rg/BS6tiwdG0dfHgjOhASg==,type:str]
          http:
            paths:
                - backend: null
                  service:
                    name: jenkins-operator-http-jenkins
                    port:
                        number: 8080
                        path: /
                        pathType: Prefix
                - backend: null
                  service:
                    name: not-exist
                    port:
                        number: 8080
                        path: /prometheus/
                        pathType: Prefix
          tls:
            - hosts:
                - ENC[AES256_GCM,data:Dg4HfEldLhepeyfrXdbQcnlixRwieQ==,iv:qi3XkqSYmbYv4qKkzSJKCUPgWVWPHDHgYhMEbqf+jPY=,tag:dFv+z+sWGw78HvIN6qN1Ug==,type:str]
              secretName: jenkins-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-20T16:50:45Z"
    mac: ENC[AES256_GCM,data:5ZH56b0DM1CfVnBmX+bCa0SO5pY16QOeLjgMBEJquIRSIBiBEyY77A+A5ITBUjaodsBS8y898N4c0HyEQviv5Voc1AjjU0gj4cK14WmQyAsgG5ecljrGzJRg81M141hAc+wYuq+T6+g7TYilLhtvmYDXuHy34kuC6Joezr7ap9s=,iv:Vqvs2nHl0Axiq4YDJZzDmDbfDOc1zv5NQQB3pRaXCI4=,tag:8FCSqMjSToMtZfFdBxUYSw==,type:str]
    pgp:
        - created_at: "2021-09-13T20:58:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/8CuVj/9VB6C9tpY5tX+mizaSH72R0aOey5m8ibsFCnUFP
            RZB/dI18a8WRD7psc8QqLa5NaTr3Ah1cbCgcCchMlj9FZKZdMy/gCkiuy9WyCcxb
            bzUvQIjhkpVYnyRN+KLKIJuXXXrqapBVi9+erXiz7lKF8t885SaoK3X5ahen2p4r
            98sJwrJJNe0MlWjokzRJGuyDg5h227R5G3jZkYnIhE5td0mbvGz/YAR2EVp4eQpq
            4MOvEhkPxIKK/cWEEBcb4TL2HWiSrIq7AKEzC6JdPAr0jXJbdVfuxvlwHZrNsQQn
            RkKryVimoB58yjkAf/MCOg9b9sW4ZW90mnUaKnvhgaLU45FV3r7bqsr21oOCyHEX
            E7DcE2RkkW4Of/Dn3f2uWhPoNyU4KI35nwE0+l6cHqT53zC1NlU2uxjbDwst/XLu
            vkfcBe5jDBY6Uac8EKsi6r3VEMbZcYz2e7P5rXvtPFTqVFFn5c4ngh2vQcJpLuze
            fyz5dTb1nHOvLNJA7XiPTWgfhIH184cWiA/c8boUWdHD3e9eRs9TnPhrUEocuYf4
            +iQsoqcyq6bt9If2kH7Cd0H7GWTA6MAL4wPyGS7cmb8YxCSyWII3p5io95HkZJpd
            N+03V+aamvLqDW/TC2poec+wiK8o42t+o+nOQ+30s+gNsmavgOph9vVocHo6PkTS
            TgFaTfkXn9dbTe9sAvCRBOsvqXmiCCmAomzW3HnFRx4/gnwlrKggLlhw2koppf2Z
            ks4nIZVSGEeBNQzlFqSqWQYsadpkxbTY8pRHgDcI2w==
            =2ixP
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
