apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-repo-config
    namespace: jenkins
data:
    default.conf: ENC[AES256_GCM,data:9jhLcB8X21BLb9mZH+os0SCfZ806EGXfpv4tR8GIZPgxOFMfbD3EL2omXjeRLqB4J96+eEnDHTQHM1wPaYPw4GaYUzktcLCWOxyQ5fqPcntQW9Hcrf7l0WEkdfUC/wH1BuTR8o0lDvuBl4OaP86T/cP88H/1+TLw/eKhcBpmVPpHhv9y+9nAxxtGjDPKGSN6OnChonHjmQeT5PvBrP380pK8zzWCnlrSngqYhhjueMwIS34pKxvngcYUgPayq4DPzrezYOgM2KwcgKNGQ6NmV2AdK1vpH07u7nVFmT4y8YR26fRF+uHmVnQDA7PzS7h3SH9xjHeTdnlUYSSprl+vdufPpU/VEjFAuUqAV83ywZ7GZnjGsrHAk9/76vfVwxddI68Y4WUyxtawMQf1T7Xntqsqlb8bRY+PYeO94kmDFnQPMODlwh63HqskQjQ3EnGnEhMafcGXGptuGM5U9ZPvGx6+JOLQQZaPK1FaiWRRScLdUTEtGhYFmMKPiXkSH/v34ucJ/Uzb1hXPa3tt58pDXRR7VxaFRCeejWRYTynmvpjBmIQk75OWOK+gUlNdbwhDz3oT+yWW2PvVFkTVNKpU915vIQxiLUBinXJew044owRUMYggtDrtKFmlChQzmvy1Ga9GVQbgUB0XLRz+Q9nODVPIKU8WGMg6mkMNJS5KLOws2hQ8mCepclr0iYHR9w6LMIwNWIZg67GoP/gZjC2JGUrFNBKlEqEmK+YjpoPgoTbX4++XZJx7cOSNPqqWWbkYzWOirgSoeoyWdwrWwoLnFhqCqsPg9XVFarufsc3CjhS/VP6kYiXfz8zVMQTn9jG7kDWrWXuM24vy4FM=,iv:zX2RisA432qS8IIqn9FhBDLmJ88EBL3hkTYNBU0DZ7I=,tag:Xxju4St6RTz6lMgFvu+cEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-08T18:35:12Z"
    mac: ENC[AES256_GCM,data:pKcnmJWYBJWNF+hVZ27ghOXD4yliZxUlaX6qlfRh01qje0yVwiMLQMcnLdUIRNP3aKWtxbEZqB6wg1Dikwhjl6tez2Z2rg4cxGZdUoUXcxgJRz4dV+6ZTLaEtOdOK443CYylZOsmc8YcVBl/rG5GWI5Qwx23F96z/eeV4x6KubI=,iv:FRmv6bi58UbXvVAI/3Z1PIAfaGVFAjh/sEGsVJaF6T8=,tag:h4amHodEyBQ0qVE+YGKYSw==,type:str]
    pgp:
        - created_at: "2022-01-08T18:35:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//RLjkaq1FS/LvW+XaMuhPme6g4AqRMbjKEPETeN3X1oQL
            q0yeFuR3LL/NwzuOJpukxRZjNmXpGc47Ggd4m6ROfkCdIVqSjH7Xm10doVToKs1p
            Fecig6KG1VAUCpbjZ3wWvzp3kxNez15YDnLYQGY7cL6oiC2gU9uHsOzJprInAVic
            AGbWjr9yrHPzh6Ho4hdxqT8nJB/IRGAR9wiw9ELGIUDkoWUNSDWZQ99S4zI/PcGq
            E18ktUbNm/fQB4XOZj+KdZXfTGxGafsfztFPROeqbjiZPKyeXdO1A3DO5JjS6vKL
            EqY4TjH3OELSefo8xO+j4FyEmkLFLe9zwje6tQiwEotGkFtUH9xGzH7NmzYIb2di
            FqD92HgbEY/MD51G2MVVQmgqYPgtBHTSgd4L6cCspRkWv9B9rupl0dqxul+dog4X
            VcUea2wulNOySpGL8yxUe3/4lMp3y8hsHHsYPV9LcGnLbElB5rkDHecpEGc5AYIk
            lPJwYu/thaH1SzEm9zzjiiA+96ey84/+8v/4/glvwaPl3kS5tPPux9iw/FjEEIW5
            +vo3phyEm41tekFkQuX9hUi2y7HED8LwuIhp9v4fLY8heCR2xWiv5WmAQlXNj+xP
            nDnm30xAPxRp09WZiZ11Kmx1lGsGKfnzMVDqyKcEKqOUdk7Ae4FWWci7ZGzKuPfS
            UAFCYbA/6gfQ0+pfdLz31tZdTuHStu5cPJDMYD7Me8j4mAloLa+ycVfFQJ2oID/0
            Fq/+aeeDNktfumk7eoEZSo8vzN3y7qNv/JvjeF6C0UIh
            =/IBf
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: repo-ingress
    namespace: jenkins
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-ovh
        kubernetes.io/ingress.class: nginx
    labels:
        app: my-repo
spec:
    rules:
        - host: ENC[AES256_GCM,data:88hMgiw0HhmzHQjioNQez9+cdNqa,iv:79gAgFSkVDV9BN7fhlnm+On5Tk1Ffbwy/r5Kin02ad8=,tag:lYXbyHK4aH9z0TM9NVDBgQ==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: my-repo-svc
                        port:
                            number: 8080
                  pathType: Prefix
                  path: /
    tls:
        - hosts:
            - ENC[AES256_GCM,data:x1slO6otWn0rJpw5N2r6UCs4wO/A,iv:gylKUzz0iKkNEVWjuUiw9oGNah88w+oXhPaORQv5v74=,tag:6+OM9Rr2Fpk62f5ydw8DMg==,type:str]
          secretName: repo-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-08T18:35:12Z"
    mac: ENC[AES256_GCM,data:pKcnmJWYBJWNF+hVZ27ghOXD4yliZxUlaX6qlfRh01qje0yVwiMLQMcnLdUIRNP3aKWtxbEZqB6wg1Dikwhjl6tez2Z2rg4cxGZdUoUXcxgJRz4dV+6ZTLaEtOdOK443CYylZOsmc8YcVBl/rG5GWI5Qwx23F96z/eeV4x6KubI=,iv:FRmv6bi58UbXvVAI/3Z1PIAfaGVFAjh/sEGsVJaF6T8=,tag:h4amHodEyBQ0qVE+YGKYSw==,type:str]
    pgp:
        - created_at: "2022-01-08T18:35:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//RLjkaq1FS/LvW+XaMuhPme6g4AqRMbjKEPETeN3X1oQL
            q0yeFuR3LL/NwzuOJpukxRZjNmXpGc47Ggd4m6ROfkCdIVqSjH7Xm10doVToKs1p
            Fecig6KG1VAUCpbjZ3wWvzp3kxNez15YDnLYQGY7cL6oiC2gU9uHsOzJprInAVic
            AGbWjr9yrHPzh6Ho4hdxqT8nJB/IRGAR9wiw9ELGIUDkoWUNSDWZQ99S4zI/PcGq
            E18ktUbNm/fQB4XOZj+KdZXfTGxGafsfztFPROeqbjiZPKyeXdO1A3DO5JjS6vKL
            EqY4TjH3OELSefo8xO+j4FyEmkLFLe9zwje6tQiwEotGkFtUH9xGzH7NmzYIb2di
            FqD92HgbEY/MD51G2MVVQmgqYPgtBHTSgd4L6cCspRkWv9B9rupl0dqxul+dog4X
            VcUea2wulNOySpGL8yxUe3/4lMp3y8hsHHsYPV9LcGnLbElB5rkDHecpEGc5AYIk
            lPJwYu/thaH1SzEm9zzjiiA+96ey84/+8v/4/glvwaPl3kS5tPPux9iw/FjEEIW5
            +vo3phyEm41tekFkQuX9hUi2y7HED8LwuIhp9v4fLY8heCR2xWiv5WmAQlXNj+xP
            nDnm30xAPxRp09WZiZ11Kmx1lGsGKfnzMVDqyKcEKqOUdk7Ae4FWWci7ZGzKuPfS
            UAFCYbA/6gfQ0+pfdLz31tZdTuHStu5cPJDMYD7Me8j4mAloLa+ycVfFQJ2oID/0
            Fq/+aeeDNktfumk7eoEZSo8vzN3y7qNv/JvjeF6C0UIh
            =/IBf
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
