apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-repo-config
    namespace: jenkins
data:
    default.conf: ENC[AES256_GCM,data:HbEBNfUA0Vk0E2/cptX/1Zpa1v6b5bM8hjEQ8iDh15MGvSbfKtbljrGRJlZFbyfOatwSJWtlF7MOEPJiOjnspuicOvmhnupXZlsXIyj5L+k4y4MlRIyoX/tkKihI0fcOjpGRBT7H6iCN0ELdC2bK5sFcJdX44f3u6LNYXA9A2UvOYf5OqtVcKg5q4pffgwSfQ7tK/aGWXfhyWYvKMcT64KFYJsxNfy0lzIpC8Oj1ZERXzsw7c6Puxyrzty6uLIF+IXHVwn5d4gPIziAOrTGmu5GLk302AoLL4Sb6++XDUPK6ajAbUK0bCWI5vLGruehsGzltWHFUi/z/Adc+LzJhDP4TW/ID7jgQqeqlqKXoV59EkyUkcrQywBYR19c5tybwhL7YoNLxQmG3mnmsCmV0D3xfvqVWTJr2j+MV4nm/5eHDJFrtPcwoWaR3+K+4BbMrvbR3IeGzYS20+BdwpV6ZXZ6cAFKT/z0wedmuk8ViMdaCWzMrw5LlxW6yqnC5YAOt95dKifDMGsElP2aCV5sThh9ua8sSd9o56EtYa2hcpFJ2RF86onhSTv9oiToIpRS8RCMtLvotOlt8VIdGwPY+v6DgCtbYmVOnadDrMHzuoGMUy4aXMOap/bfzMfNiUbUYDjyrPEBZCAR+VB7hfteZl1Z0S3uazuXtiTSy4xkk/l7FhKeQpPff7NeZK0cwQqqPRrhJL1zk+Xy3hrLQHUXdNblTOFfxqI9q7QxGaTMUFPo0LEGiyfaLP/G/bul5HCMsffe6OWvq1MkcwyUwOP+9dpHCe1ZYcUCXv0zfo4fCZ854enITyRIYyJcikCW123W2sXhabPHw0BK0FHQ=,iv:I3RbBghq7BFjjUtugogY1Y8SXPekJ/4YwSBSDgzgpX8=,tag:2hrmHHwC6kd4tOv1niwPAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-28T22:41:02Z"
    mac: ENC[AES256_GCM,data:iULVBymTGYybfw1dkHtNUNcrRKTYtHrRMilmB0bMJ61rrUZQWYHSywgGVSjIaxcaopgkO+E65aPLJEJl6qHctPnz4RBhGnD2B2YuVbbPYzklMTvvRwAGOMMi9RgBUdWUgLf0vz8agtR4EZmwiupMPU6t0Prs7HskTVmShjsH5AU=,iv:3wGmxF3o4n1paXa+Bvj0mCYpWPitTVaEQ2TI7uf2OUI=,tag:lT7Kcl49l6NLo/2gD+c49g==,type:str]
    pgp:
        - created_at: "2021-09-28T22:05:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/8CnmNZRz5v1TzrAemeNQjbOH5FCxl7PelXrrR2m2K/hd5
            xbxO4pyvMXaK1F9UH4oXaHYp9eokXAwF30Z0REquONdCtUs4KwHSoLNxKgctxWiC
            CsEArW9sCWYeysR8J4lCxG1xDN70izmAB8H4t63jUI0Ut9ZLvbFEuTkNv3O14ljp
            tUz1t4MkTA7j94Qy3AczPaX1x9zUvDehhUvJCAW3GQX0TEHp9wIBpD+L11+WbwFt
            VGOxKNThU6WXosTyNZCmjLoG0CnS0KYMrQgx13+WE1BGTHiP7adO9fmOMNLjIXKV
            Eu2Jpo9K6jwTE/I4qlCPr66bEY0m1HZ82QH0V8/RW4MJFzQJ9lOY/N0853yVc9kW
            9sJ91o0szsHaLtnfQlb9/f/OwCWF7NNPeJiz9ZJNzH373WzYfBNSh7STNSFrwyyp
            yrnvaakVIy6KJNoCiZq0I8/fRfOFN2v694s0GrPUr5ANqcUG+Dmzg3ODLcGnUJJL
            rlCfT/W7OZbq+hZeFAP718r2EsjKzSLLojNX89ov7fRHdfciObfW31q7bNQ1YHdh
            0S/PCLaXS08OTXX08ttwlY0NsE3Fwsni4Uo1pnsJWMe5BZUaJCbB10LtK5daQrva
            hKZhi358fWLEDHtE+GrMc+ECXpvayh8Om9nWcv8yMzJtFeIc80j5r1udER56aKXS
            UAHPtjjGMgZ/Asy3yonbzwb9Ic3uCn/kIw7XZtYnWzbQKHpkiseQubhjghKZ0SL0
            lZNfqZBk3mBJKRxyX1agpVDbkq6O+jBg0lKiYFciQEl4
            =jV6w
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: repo-ingress
    namespace: jenkins
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-ovh
        kubernetes.io/ingress.class: nginx
    labels:
        app: my-repo
spec:
    rules:
        - host: ENC[AES256_GCM,data:sx0SC+Vy7GMvCKXcz5JkH9JWrc3d,iv:NvC8ZiD37d52nsIlPhR4KainsvOJBk173cXq/7mWCc8=,tag:wChRuylQL9zRbwW3jb5yFg==,type:str]
          http:
            paths:
                - backend:
                    serviceName: my-repo-svc
                    servicePort: 8080
    tls:
        - hosts:
            - ENC[AES256_GCM,data:aS2L/4Tsv7+esDgC5Pq/kitMev2j,iv:5hUwKq0lNnexIncgRDO0rt7QMOA2zjL3J3EIc+EBZ9U=,tag:TLZtJeGP2wejKPPeuX6DQw==,type:str]
          secretName: repo-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-28T22:41:02Z"
    mac: ENC[AES256_GCM,data:iULVBymTGYybfw1dkHtNUNcrRKTYtHrRMilmB0bMJ61rrUZQWYHSywgGVSjIaxcaopgkO+E65aPLJEJl6qHctPnz4RBhGnD2B2YuVbbPYzklMTvvRwAGOMMi9RgBUdWUgLf0vz8agtR4EZmwiupMPU6t0Prs7HskTVmShjsH5AU=,iv:3wGmxF3o4n1paXa+Bvj0mCYpWPitTVaEQ2TI7uf2OUI=,tag:lT7Kcl49l6NLo/2gD+c49g==,type:str]
    pgp:
        - created_at: "2021-09-28T22:05:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/8CnmNZRz5v1TzrAemeNQjbOH5FCxl7PelXrrR2m2K/hd5
            xbxO4pyvMXaK1F9UH4oXaHYp9eokXAwF30Z0REquONdCtUs4KwHSoLNxKgctxWiC
            CsEArW9sCWYeysR8J4lCxG1xDN70izmAB8H4t63jUI0Ut9ZLvbFEuTkNv3O14ljp
            tUz1t4MkTA7j94Qy3AczPaX1x9zUvDehhUvJCAW3GQX0TEHp9wIBpD+L11+WbwFt
            VGOxKNThU6WXosTyNZCmjLoG0CnS0KYMrQgx13+WE1BGTHiP7adO9fmOMNLjIXKV
            Eu2Jpo9K6jwTE/I4qlCPr66bEY0m1HZ82QH0V8/RW4MJFzQJ9lOY/N0853yVc9kW
            9sJ91o0szsHaLtnfQlb9/f/OwCWF7NNPeJiz9ZJNzH373WzYfBNSh7STNSFrwyyp
            yrnvaakVIy6KJNoCiZq0I8/fRfOFN2v694s0GrPUr5ANqcUG+Dmzg3ODLcGnUJJL
            rlCfT/W7OZbq+hZeFAP718r2EsjKzSLLojNX89ov7fRHdfciObfW31q7bNQ1YHdh
            0S/PCLaXS08OTXX08ttwlY0NsE3Fwsni4Uo1pnsJWMe5BZUaJCbB10LtK5daQrva
            hKZhi358fWLEDHtE+GrMc+ECXpvayh8Om9nWcv8yMzJtFeIc80j5r1udER56aKXS
            UAHPtjjGMgZ/Asy3yonbzwb9Ic3uCn/kIw7XZtYnWzbQKHpkiseQubhjghKZ0SL0
            lZNfqZBk3mBJKRxyX1agpVDbkq6O+jBg0lKiYFciQEl4
            =jV6w
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
