apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configuration
  namespace: jenkins
data:
  1-create-credentials-telegram-token.groovy: |
    import jenkins.model.Jenkins
    import com.cloudbees.plugins.credentials.domains.Domain
    import org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl
    import com.cloudbees.plugins.credentials.CredentialsScope
    import hudson.util.Secret

    instance = Jenkins.instance
    domain = Domain.global()
    store = instance.getExtensionList(
      "com.cloudbees.plugins.credentials.SystemCredentialsProvider")[0].getStore()

    secretTextTgBotToken = new StringCredentialsImpl(
      CredentialsScope.GLOBAL,
      "TELEGRAM_BOT_TOKEN",
      "Telegram bot token",
      Secret.fromString(secrets["TELEGRAM_BOT_TOKEN"])
    )

    secretTextTgBotChat = new StringCredentialsImpl(
      CredentialsScope.GLOBAL,
      "TELEGRAM_CHAT_ID",
      "Telegram chat id",
      Secret.fromString(secrets["TELEGRAM_CHAT_ID"])
    )

    store.addCredentials(domain, secretTextTgBotToken)
    store.addCredentials(domain, secretTextTgBotChat)
