apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-repo-config
    namespace: jenkins
data:
    default.conf: ENC[AES256_GCM,data:DSkdFdoTYruc7ZGDxVzKH1KCLxRhv+NeP7PNVhG1DlIWmArsSI03SZCS5MmY9ubxhhzP9AfLMKyRIXlPbpNxWdlmf0uRI8lxW9PyO4s1wVVxajKHfB9+jkLu3eCnQAoh25v4V3r+44hhMWad/F9Ta84h30uiAKU0xm8xU5VVDRoTGmHx4Eooe0ttWA2HMPLozGFUi/lfsJMiXlQA6wA/nXV53mfVPz7UZwPRsblGMwarIruOQup1whGzhbyTfo5nP3qfREYoPaaMcSYa7vTNSEx9t6qOhzLF8jpxntgbcsTut+BccTCzVTLRNdo5wlNjEG6eVxaBDX7E0FwpriIKuRfpESwSpgI6PMew26Y2MUl/sgSt5kP1TZfXcO/lE/1Zww8oNiFl1QS1nzaJtmF33aOY/ECtJPc5fkKIeyM2wykeKxvqELXGzffY0FuoxPTM+jUDAWiQbcMnhcPg7VPt8YtOLfB72C8gzvZCahS70g8kvHwCPfxk53tMyK0lnbHJvVG9mv4mgep5Os5FaHSJ229r1pz4R/uvCRoaZWPvPuk6lcFnPpQNeM5uhu6Rdr3BIen3KdmX4kMhi4MoBpg1GUBK1Bdddd/5XnhGs1IKQHCaoC8q1DKEEehwUT6qbCKT2zBCNhoA9aAJZmZWnxaV+swoeMTeV8LwktyvVt0DPh6KzrMgOfFOeFG6dq0SoGYEZ6h0cYYU9AnSK2/UzxLmHAvdXM/mY8pE601zcXUhBbf2Tb8B3LRYxkG8k7oh/kugkAjEfhL17BpHFphvnQJbzq3h2zWN26jXtIFSiU3jjG+PNsVnF7JNxZssGMAr2nqUrqRoH5KFfEE6k0c=,iv:zUxGHdHPFbIjxtkiUmNNFCdOhvjaps0S6P7P+HxWeu4=,tag:gOjM33zrPxf06Dfw3aGZhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-08T18:29:01Z"
    mac: ENC[AES256_GCM,data:SxHaoDQW6W7ielKCLKgB5JnGs+u3vQrm4Nd9jGIhnRYmKvsqg1hPiRvSt03mI+jg+dFDpV+nyYmbctyoLGh7KLWtz6RoYgnur6xsiyH/+Zy77Nuqd+UJybjx/u/ReQcSURkb2G761tnyfX0cnDfIjrQAsepaYul+ns0K4VNhZbY=,iv:q5gSEQ+i3D53FxUBKEdy2RPm+X/lmpNbTOh3O6wcX4Q=,tag:WzrxamgF/tL1lpkQhhXp8A==,type:str]
    pgp:
        - created_at: "2022-01-08T18:29:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/9GbEW3jhix7izXVVcdaqYjrlpz29rANrsN3NrDhmQJeSL
            9enKJnI70CsMhnAKWJI45DO5jXNP8lYR0AW2vjirFRDO8APqyRWe2/4LOVNY479Q
            nDdmh9Cth5EZUHzDB35EAoDj5l2z9rT02HQBzIvzcVN4jQoQj/JtKqmYlacyD5KS
            WxKz6gkXvO6JOUvi0PfEsOAri191rAI13JSIZ7ulZNG6u+fO3IjRWZRBQSFwnhlX
            xq2Yezr8s1aO9q7ROO/cZwtclTsJ1JSKx/1t4VxW98gpS0OtgzYA55WJZAkB/jXX
            4fLD9SoOgR5ea774vKaT/V8D1lPPhhGaLDZxWxn9SlD1BgCcK89vh3M+ueXK39RK
            mQTJH7SK6zQEUQz7l/+oHCJ89jXK3wxXT4t+FFk4tsii39iZy8IEHcADkBUraTJU
            5jldM9LFApGKPxHNt+K8+weqEgCV46rr7/f9Tn67nbEdSmLcvnYc3IgJOygneLYL
            00kVL577gkIpFsbvuRHxzDvMpUplNXXmJGkh4wg9XS4scSvSo5l/b9h7/F3MbkWb
            Je+ZVkotDm2+dIq/lqoPIPhQhJmJc0mMF13c0mOJe4d2FojI9E02dponX7uzIxLJ
            k1ipUcslHdkMoKBUwNClPYXbKyPa0yD/vRI3vwW1n8PWKCIesvoxv5FQDPk6YwrS
            TgGUJ1hswr2G4AjLbGVX8HOVQG005MMY45FM7d9ARJTKDEXrV8O6T6Hs8LwNRhHI
            DKFEBvbH9f/fd+WTGMcamKxfX+SzFVGdR+rqcl0Tcg==
            =QmeI
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: repo-ingress
    namespace: jenkins
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-ovh
        kubernetes.io/ingress.class: nginx
    labels:
        app: my-repo
spec:
    rules:
        - host: ENC[AES256_GCM,data:DdIYe9/Qf/JLwi4JiW3U+sgHeogH,iv:3OLKNBFJSh0QZFszBduiyJaZ1s8tIcklKONMkA1JYNY=,tag:qZ6aJ9FmkLFmTFvrNxetCw==,type:str]
          http:
            paths:
                - backend: null
                  service:
                    name: my-repo-svc
                    port: 8080
    tls:
        - hosts:
            - ENC[AES256_GCM,data:piAZgyNhEu7dasr/3PxhzpFINa2j,iv:2kcDRl0nHlrV4keHTmm0pkO1VoStiX/6XwGVwLYygYo=,tag:GPqy3Kyvo8abfQflL0qxpA==,type:str]
          secretName: repo-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-08T18:29:01Z"
    mac: ENC[AES256_GCM,data:SxHaoDQW6W7ielKCLKgB5JnGs+u3vQrm4Nd9jGIhnRYmKvsqg1hPiRvSt03mI+jg+dFDpV+nyYmbctyoLGh7KLWtz6RoYgnur6xsiyH/+Zy77Nuqd+UJybjx/u/ReQcSURkb2G761tnyfX0cnDfIjrQAsepaYul+ns0K4VNhZbY=,iv:q5gSEQ+i3D53FxUBKEdy2RPm+X/lmpNbTOh3O6wcX4Q=,tag:WzrxamgF/tL1lpkQhhXp8A==,type:str]
    pgp:
        - created_at: "2022-01-08T18:29:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/9GbEW3jhix7izXVVcdaqYjrlpz29rANrsN3NrDhmQJeSL
            9enKJnI70CsMhnAKWJI45DO5jXNP8lYR0AW2vjirFRDO8APqyRWe2/4LOVNY479Q
            nDdmh9Cth5EZUHzDB35EAoDj5l2z9rT02HQBzIvzcVN4jQoQj/JtKqmYlacyD5KS
            WxKz6gkXvO6JOUvi0PfEsOAri191rAI13JSIZ7ulZNG6u+fO3IjRWZRBQSFwnhlX
            xq2Yezr8s1aO9q7ROO/cZwtclTsJ1JSKx/1t4VxW98gpS0OtgzYA55WJZAkB/jXX
            4fLD9SoOgR5ea774vKaT/V8D1lPPhhGaLDZxWxn9SlD1BgCcK89vh3M+ueXK39RK
            mQTJH7SK6zQEUQz7l/+oHCJ89jXK3wxXT4t+FFk4tsii39iZy8IEHcADkBUraTJU
            5jldM9LFApGKPxHNt+K8+weqEgCV46rr7/f9Tn67nbEdSmLcvnYc3IgJOygneLYL
            00kVL577gkIpFsbvuRHxzDvMpUplNXXmJGkh4wg9XS4scSvSo5l/b9h7/F3MbkWb
            Je+ZVkotDm2+dIq/lqoPIPhQhJmJc0mMF13c0mOJe4d2FojI9E02dponX7uzIxLJ
            k1ipUcslHdkMoKBUwNClPYXbKyPa0yD/vRI3vwW1n8PWKCIesvoxv5FQDPk6YwrS
            TgGUJ1hswr2G4AjLbGVX8HOVQG005MMY45FM7d9ARJTKDEXrV8O6T6Hs8LwNRhHI
            DKFEBvbH9f/fd+WTGMcamKxfX+SzFVGdR+rqcl0Tcg==
            =QmeI
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
