---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  endpoints:
  - honorLabels: true
    targetPort: 8080
    path: /prometheus
  selector:
    matchLabels:
      app: jenkins-operator
      jenkins-cr: jenkins
...
