---
apiVersion: v1
kind: Namespace
metadata:
    name: postgres-operator
    labels:
        infra.gitops: postgres-operator
        prometheus: scrape
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: postgres-operator
    namespace: flux-system
spec:
    interval: 10m
    url: https://github.com/zalando/postgres-operator
    ref:
        tag: v1.7.1
    ignore: |
        /*
        !/charts/postgres-operator/
...
