apiVersion: v1
kind: Namespace
metadata:
    name: postgres-operator
    labels:
      infra.gitops: postgres-operator
      prometheus: scrape
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: postgres-operator
    namespace: flux-system
spec:
    interval: 5m
    url: https://github.com/zalando/postgres-operator
    ref:
        branch: master 
    ignore: |
        /*
        !/charts/postgres-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgres-operator
    namespace: postgres-operator
spec:
    interval: 10m
    releaseName: pg-op
    dependsOn:
    - name: nfs-sc
      namespace: kube-system
    chart:
        spec:
            chart: /charts/postgres-operator/
            sourceRef:
                kind: GitRepository
                name: postgres-operator
                namespace: flux-system
            interval: 10m
    values:
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 400m
          memory: 400Mi
      configPostgresPodResources:
        default_cpu_limit: "1"
        default_cpu_request: 200m
        default_memory_limit: 600Mi
        default_memory_request: 300Mi
        min_cpu_limit: 250m
        min_memory_limit: 250Mi
...
