apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-data
  namespace: grimmory
  labels:
    app: grimmory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
  namespace: grimmory
  labels:
    app: grimmory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-bookdrop
  namespace: grimmory
  labels:
    app: grimmory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  volumeMode: Filesystem
