apiVersion: v1
kind: Secret
metadata:
    name: grimmory
    namespace: grimmory
    labels:
        apps.gitops: grimmory
type: Opaque
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:ZEp85W7CCw9rO9gLAJOVlxr+M7i+g6DzJHkp,iv:qnHmre6o21V4OYkZ5JQwnJtYHAsL9ePTIJ1XxP/1mqI=,tag:yBbpO1OpOAvwEg7SbYBQuQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:7bgwUbA6yoXKxoe1VpR5PqfNZxxuCJb6lDfV,iv:6rMAae187+nYKjTfwATFnMZX/wJUupAoephyXFXHsww=,tag:10XonOS0o08ksroWLC06qg==,type:str]
sops:
    lastmodified: "2026-08-08T18:22:21Z"
    mac: ENC[AES256_GCM,data:FQYPPBn4y9Ns4AWHjek1vIrz0yaU/nau5k6uDQ3Bh2Ey3Z87hlga2TRc0Xafz3VDEgkezMw6jcyO+sJWDqukoUhg+cxe3A5j+uk9pMHrqwutfYEQOQ4pl4RPDkJ7jGMHbcwputSiDTkLCu7vsjGYVWk+RxHffz/Q9U4KpzrJ9Hw=,iv:lFG5CsVJkt9ErlMs7BN976UZCNJozQEB3HVnLoG1jEE=,tag:/WkAPeusJ93oIVyQqB/80Q==,type:str]
    pgp:
        - created_at: "2026-08-08T18:22:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//XPJ1HBZuCe3yT38gkBma4FziuEadJ7eKgQqv7XnIwkKk
            6GR/+p6z6N/XmlTu5yM674V8g0spGYnvcgAOfkopujCB+/7xB2cgMJ5XmXPBhuYt
            NP8WM+gkrU+PQ9xP8vTAKKAWPOpp6LEQ169e6GGxygEBSbL3VM6LyB7Payz0KP4X
            JfgaaV71RuDg6dF9p4LLm8QIPHcTfPqcJrPbPgE7F37uWYo9rkltd6E6lmFvFnDq
            LghG3x+CTxBLQiCwYbxQUxRZvsOoHcNRDbllXdmjGSzW6E8//KQhDbF9Qyz/BBmK
            ic3BGtvTvpOYRjh5BPaJ9NNWgEpL7xRxirlVxd/GQphEWFngf6hCTKK/cJa5fuSI
            BbrVvOl257SrARat7XC25dqVCT70xcoQD/sQp1yeKdgguYMfn6zsLMMhCuwPnrbx
            jmyucTXdmszGia3OPB36PNbWZolm9+cjL2JV/DdDYpgd2VWMPMEpa9f70g5rfgYY
            YhQ/nDhOKV9dWVVIVoSLvxN714fzbJS2WzxpW5b1Grgi5DcFWAq/xYQMcOpOoN7b
            PbqsET2MmR6ipVYOvVpVJZWelJ98eeEWEhBlbhIGzfOTBCyJ37jaWe+R9fy50gPE
            1AYbkXoJ1czq7RTgY62FKmshImUsnUHvqHVB4iLL3qdSZs9oVWUZEqbFH+fQvSLS
            WAHLZRxb3+80giqkRhP7wZE0S5gKbfvbXfrN6K3wbYovs7QFyukLDZ5djEbd9rcK
            xsXMeUZpcrsVsA//l+FwOuKajWFYtLiX9d8it4810vKGtGoU5Ra5K2s=
            =dKb/
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
