apiVersion: v1
kind: Secret
metadata:
    name: grimmory-backup
    namespace: grimmory
    labels:
        apps.gitops: grimmory
type: Opaque
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:mxGL5Vs5540wrAYam2wz/Ty0AbyKs5rYqTxmwQ==,iv:UF6LairE/3Z6WeV9JrznJvj0RiqxFPezQTsvVBe/pXg=,tag:elNWX7V8kTdr6+mjGtAgnA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ZiZsff80sTLUMBrzEMgP,iv:EybGEmn/Rxk0p4gQsRf4G+9GZ7yimFsH77lXW90qHIY=,tag:s139lS0/WQDQ8v2K/ZSKPw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:gg52/BRmszkCPdl3W6iuey21,iv:g6J03Z5QRg28t0SEE4UwW6b/FkbEHMflnYRsuwf7kGA=,tag:vjV2ASl+GPIaywfiy9BaqQ==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:5PA4JtPfRmNh,iv:ZT/XYMn2EuMAiaWND31MAtGiXZGi5sTdAKuLlkOb9P4=,tag:068iNZU4v7L+835/VJ0cMw==,type:str]
sops:
    lastmodified: "2026-08-08T18:22:03Z"
    mac: ENC[AES256_GCM,data:JFpgXd3x2dFnUpXTW+vbXyO7k/dl1t865uDpRTfd7uigo0nqkBi1BNGWZSOfsuODetL0zRsN5POKPxbb0mmsGQ1h2qXpgO1RC7AERKlq1UVp0jE1WRXJ5553U0I4oe3urzyYdEEMqV2/YCIZ3pPnPEijOqfu7DeY/5wPrmIgeaY=,iv:Gl/guo/mbaeS570s3ITH2KdWSz/Pu35In2a1Elw+Ras=,tag:aO2zbk+6yQNeknZccyUE0A==,type:str]
    pgp:
        - created_at: "2026-08-08T18:22:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+Ii9EjBjFFNgB0bjpED5KeyRrdtCXFyiz9xG+ON7kMkm2
            sr+e1XVKd7iaYWTyMPKJBdQe3/8+z6urqtt4zhs6uGeAB+/HrD1NVnMADf+akK32
            /sjRjjBSsj4brexYLald4EZOGENPvgMFjqVtJY0nQnYSGX56G9Y0UbO0uCgPkiJt
            RXgJmut1ld3WQfry5iZlB2F86GYatS0kCDdK3RKLY7DKWHaB1vtYQzXNgppDK1mv
            ySbg6wa/hfwLQmzQ74sBdQy+d/jgVV2w5oEEVZB8EtME3q4U4w/hr67s1q+JB8wJ
            KOg6w1L/ge684NR/+I3RvOov85Of+yt5GWB0+dyEzVik87o8p5CB0X9MhZ+ZbGrL
            MzRz7IxYPiHAZ0zrtQK+DY2Z4Urqz0z0Nc/HvoFLe4NXUvMruflplS5PwEwRZUAs
            h0y/0onacjVvR7KhNYSsZiJfOzNyMxe/VhiZy9v9NI0OPx+MGhYwCNyt098nKSTW
            Rigq3lB64VTaWkJceSEfbLh9QWfRTRUJ4+UywZ7N3bo6zhqDNFkdc2DKPOkreZv1
            Vdu79IcPlbsC+6RaOtHICtImtecnd6gjkgxVBKVlX5wU74djwneZXvfKdRRRNELb
            77uql7bQnu6D9fCcwvQ/GwgTeyk01d7E8SfYlhWxkm5ukn7KPkZrQZ1i+263BDTS
            WAGyY5xc/GfZGVul9rh9++uZ4yVEJiZ+Q89ax6/HdONPiO6qZ7hWyGuclviVznuN
            1hp7QnmrOxUJDRpWjg1MUYlTkKxSkenqJEfflQG1KYhKmJzdUfG9+T8=
            =Xe4B
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
