---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    infra.gitops: ingress-controller
    prometheus: scrape
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginxinc
  namespace: ingress
spec:
  interval: 5m
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginxinc-ingress
  namespace: ingress
spec:
  interval: 10m
  releaseName: inc
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginxinc
        namespace: ingress
      interval: 10m
      version: "2.x.x"
  values:
    controller:
      name: nginxinc
      image:
        repository: docker.io/nginx/nginx-ingress
      kind: daemonset
      nginxplus: false
      enableSnippets: false
      ingressClass:
        name: nginxinc
        create: true
        setAsDefaultIngress: true
      enableCustomResources: false
      appprotect:
        enable: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      service:
        create: false
      hostNetwork: true
    prometheus:
      create: true
      serviceMonitor:
        create: true
...
