apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: postgres-operator
    namespace: postgres-operator
spec:
    interval: 10m
    releaseName: pg
    dependsOn:
        - name: local-path-provisioner
          namespace: kube-system
    chart:
        spec:
            chart: charts/postgres-operator/
            sourceRef:
                kind: GitRepository
                name: postgres-operator
                namespace: flux-system
            interval: 10m
            version: 1.7.x
            reconcileStrategy: ChartVersion
    upgrade:
        crds: Create
    install:
        crds: CreateReplace
    values:
        resources:
            limits:
                cpu: 400m
                memory: 400Mi
            requests:
                cpu: 400m
                memory: 400Mi
        configPostgresPodResources:
            default_cpu_limit: "1"
            default_cpu_request: 200m
            default_memory_limit: 600Mi
            default_memory_request: 300Mi
            min_cpu_limit: 250m
            min_memory_limit: 250Mi
        configKubernetes:
            enable_pod_disruption_budget: false
        configLogicalBackup:
            logical_backup_s3_access_key_id: ENC[AES256_GCM,data:6xgOy0MMtyP/8P3uguB4,iv:3ByjBjADGBxTtv4u24XNsdgXNntrlo02KZk+Ts/mL2U=,tag:LAF6Igj5v7pYgkBCXXdOmA==,type:str]
            logical_backup_s3_secret_access_key: ENC[AES256_GCM,data:N11LuKEYUCHHAgSQevpH3y99,iv:orCILDSIVyxqGdBgzd0AnmCpk6lj2Z+Z70fJGw6TWRY=,tag:xwxe37BoDZxX8UTZO2xL9A==,type:str]
            logical_backup_s3_bucket: ENC[AES256_GCM,data:pqbsX/gSpz9/,iv:LIgDtjsW6G4gnlzfGfRmZ71S6WcLkMQhzYwjs4/zAMc=,tag:uH9MHlSPzQfmiuaozzmyEg==,type:str]
            logical_backup_s3_endpoint: ENC[AES256_GCM,data:3QDL0br9uy7PomMMD0MPrT6ECYw587rahP1blA==,iv:y5hoOzLPXr2Pc4pGyX6Yt0YUmwCUDWOl213bPaXisPQ=,tag:WEv1ZeApoSNTXajAUu/PVg==,type:str]
            logical_backup_schedule: ENC[AES256_GCM,data:NMRaFQk9Yq6i+/s=,iv:Ol2yiLBc6dvYthD22HoiIvQZKqtdrDa55y0kFU8ZoFI=,tag:LcCldmVrMzAeM7eTWJKbdg==,type:str]
            logical_backup_s3_sse: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-02T13:47:43Z"
    mac: ENC[AES256_GCM,data:dWw3EfgiAwYxdPC5QXsLU+vC5Gvh/pbroRs+pZ16u2ywbjee+DOq7P8x+x5+CVySBYA2Lv9zIm+Hzq2wleAJHg0Jqk2Nd/gDW/o8Ipnal7glBunAUCCQmp4W84xk+tIgMlS+bX+PNhQYWCAH+QYAYjRIbfl1LPDtWKJK9ggk5t4=,iv:0AZTTSxUmBfTEnWFwiJL7yFbey8LMwsPE8h4DbB76ic=,tag:g4CljGauJpfR9vo8bV/1dg==,type:str]
    pgp:
        - created_at: "2022-03-02T13:47:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/6AuNtNMLlqC92jEz1hjV2vmQeF3ElG9C1h6+GXgBK1+bW
            gdGpwLmLJfTg2NoXoPZI9XcoYbnLbxFvqNXeQmIlKccmSB5qdrBQUMp62g7NbK8a
            SO0+xha2On0DOPbaPEZ/aTb9U5tnyWifElWKyfjbCteIkc5K7IfcZfp/6S0YofNz
            Wf2aPi3ZigQrpGmgawZsz8jvOvK+n14TH1ES9h+T2jcm202VVnXesSqTxYw6ehfI
            iS1690rZfU2j8TaTr+7q2TCLEOVtl7BUOEs+4G0tNFBsD8zd87uTHW5pzmskKu9h
            okzciTtjfnMa9EmyWmo+IyZlKEzu7dHX7IYpcy4QPPPTrxvXbvJ9m3zYTYzpK+xS
            wDfiGUWUO+ig8JDDHPUOO2iak4MWjcB1X034wrn9j1lmgC9Jb0/4+a2qSUbVq4el
            xo1mToQYqy6aBttJhTj8LfQNI5nwss9lEn+7EA84fiDzIzwN0szIMyQC/t1L2iGq
            nguem3DV+KyjkxKw5pOe16uWFEqUhj8oH5+Bk5U8kXfmCD4PYmPL55+dwhqn1gRR
            kK9UCn6zDpfJEcLyDCDi8sr58rma1h9oL6pbv5fD58WlzrYRIAn3fvte6scTNN5V
            6i/GhSOam+hQ82pUiRH9ytJrGhmdz/BEV1QlhEugcoiE2vSoy1ijXw1gFbZFAqTS
            UAFVs+s8SpN6BPRShWuMyTTYQKhY5uMjNLPvRuIh5tsH3nzHMclXEDvzNOSUGg00
            RBws+aVr6hqasqR+o0oWFQcU/x6wDhkzWgNzF4dA7P7x
            =EVqp
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup)$
    version: 3.7.1
