apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: postgres-operator
    namespace: postgres-operator
spec:
    interval: 10m
    releaseName: pg
    dependsOn:
        - name: local-path-provisioner
          namespace: kube-system
    chart:
        spec:
            chart: charts/postgres-operator/
            sourceRef:
                kind: GitRepository
                name: postgres-operator
                namespace: flux-system
            interval: 10m
            version: 1.14.0
            reconcileStrategy: ChartVersion
    upgrade:
        crds: Create
    install:
        crds: CreateReplace
    values:
        resources:
            limits:
                cpu: 400m
                memory: 400Mi
            requests:
                cpu: 400m
                memory: 400Mi
        configPostgresPodResources:
            default_cpu_limit: "1"
            default_cpu_request: 200m
            default_memory_limit: 600Mi
            default_memory_request: 300Mi
            min_cpu_limit: 250m
            min_memory_limit: 250Mi
        configKubernetes:
            enable_pod_disruption_budget: false
        configLogicalBackup:
            logical_backup_s3_access_key_id: ENC[AES256_GCM,data:Zm8/v1O5/9NajfGc7LDE,iv:Br9IQo+kXiCXv3RqrgqrURKn6PIEd2VMYCqtHMv9zOU=,tag:dGlD1GPdFibpdqoVQbny5g==,type:str]
            logical_backup_s3_secret_access_key: ENC[AES256_GCM,data:KN6oMK1WCE+LnOMNLhypRS9S,iv:qAaMlzM44AXVJGGBL8Mp3clnrfXoIdRS+IDQJjTiZsM=,tag:8bEQBr/hXaORKv/cnpVDGw==,type:str]
            logical_backup_s3_bucket: ENC[AES256_GCM,data:aEFVfCjlvdAZ,iv:ryxFyD5fTbcvjh2zoUKRmntm71fTU37J77FCEqocEjI=,tag:pO3ttiX03+FgkMFZ/BgqPg==,type:str]
            logical_backup_s3_endpoint: ENC[AES256_GCM,data:ud5E/2SEn7Hmc440+LVenhemjW41ycWPj8ZoEA==,iv:eyDQnpPWQolJ4GHdiwPC4ao8bsv1L2t9+BECmF0xqCU=,tag:z226+Tm2nmFgS+XEP0xMdQ==,type:str]
            logical_backup_schedule: ENC[AES256_GCM,data:Q0kf92KlAElH8k4=,iv:sBNzQ96E2VPtyeQWu5uesgjOimokANRafXlhfQl3bWQ=,tag:U256BwQOVZYM50TsGZtbVQ==,type:str]
            logical_backup_s3_sse: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-31T17:02:02Z"
    mac: ENC[AES256_GCM,data:V0+K2/fWTIq5CLC8EssZ25CLoJ/9cuk7yO9E63hcsrjXjBGa3OpL8hQsUdKxg96DZTqqn0bg3+nSkVMtEyXA0Sjah1dNwhitGENy5tDggsh2CdtzGU7xY7u4eC0YZepzYmV1VzLCtQeWMxS0go06SVaS1ySPEdLbPuxz+jbBftQ=,iv:gNfjpWMkPhnhHdP4c6jk6ZytIHcGpQJzsCh4IpuPgnQ=,tag:XSisWg+yafTfu6Xi3If2ig==,type:str]
    pgp:
        - created_at: "2025-12-31T17:02:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+P0udFc43wcZlCxXURibX6KW0Xel1LhkwJpHYVewunapo
            PDMEJSZEMA0cdUOCZW3Qew4kFD6BUhOtgEuXOlLTrVBkj6iAUTZrwl7VumldZavj
            9+c3PC7py0E1oq6QUGlAUSlREm9FMuWlFI91reANTn73ZGzVmxfpR5pAHSLeNZL+
            Gol0jC9k97mDN3P9ZiDveLKwFNzGB2AVtbq3QEcAlrJST12JeOkUyO8MPBpNh/td
            b0u/LOBb2+LGeFNVbD8cZxxuNLPmvCAnbZ+Y7ytILix8w1Fp3sELaMPrD7Cw5dJx
            d/xRaPQn13xuPenkRekix7K/xjl8536kAux7/gM/J7Ni0s6/nV0jWGLSvz9eHqvS
            9i+V1ZNKPDZk5QkRmcet63ok7saBh9Nf9/xnlB8ikhGb+WjfY68Lx78tDJsS3DmP
            c4XkUyB3XLgwdA6iEyXx0n0jDFdjTFf1Z13KQL8j8EmhPFGDjMJKyspuzpJt7MwS
            ykn5+KuvdNA4hx5Ju/viPMTBkqbl/fu2RsA8+eQ1vDjEL0vCMJ/BiUfO7D3zC8tF
            DGqDmM34fxXcPK1McnvamSJTA73FDjek5NheztLQqA9gkucp3KsuNSYit1WrTZPe
            dRR/ObSYpx/TLKiCeONrpJ/U9QyZ97cG3uJK2MjX/GaDgA4K3y0j+blmZc9ENWHS
            WAH1KvZKeUAkUJ5GESDO7E8Ihzi3SajlGT89PsPd69BSqC1bkyCilO6RhHsXjhGr
            TcqMQWDPxCNsOsbeHvcg00juX6ZPITzLFoQjY7bCE4j2ty6mnTHzbcU=
            =oAb9
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths)$
    version: 3.9.0
