---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: falco
    namespace: falco
spec:
    interval: 15m
    releaseName: falco
    chart:
        spec:
            chart: falco
            sourceRef:
                kind: HelmRepository
                name: falco
                namespace: flux-system
            interval: 10m
            version: 2.x.x
    values:
      scc:
        create: false
      driver:
        kind: ebpf
        loader:
          enabled: true
          initContainer:
            env:
              DRIVERS_REPO: http://my-repo-svc.jenkins.svc.cluster.local:8080/needrelax
      collectors:
        docker:
          enabled: false
        containerd:
          enabled: false
      customRules:
        except-jenkins.yaml: |-
          - rule: Launch Ingress Remote File Copy Tools in Container
            exceptions:
            - name: jenkins_pod
              fields: [container.image.repository]
              comps: [=]
              values:
              - [docker.io/jenkins/jenkins]
          - rule: Contact K8S API Server From Container
            exceptions:
            - name: jenkins_pod
              fields: [container.image.repository, k8s.ns.name, proc.cmdline]
              comps: [=, =, =]
              values:
              - [docker.io/virtuslab/jenkins-operator,jenkins,manager]
        except-sshd.yaml: |-
          - rule: Write below root
            exceptions:
            - name: sshd
              fields: [user.name, proc.name, proc.cmdline]
              comps: [=, =, =]
              values:
              - [root, sshd, sshd -D -R]
      falcosidekick:
        replicaCount: 1
        enabled: true
        config:
          alertmanager:
            hostport: http://prom-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
        webui:
          enabled: true
          replicaCount: 1
          redis:
            storageEnabled: false
      falco:
        json_output: true
        grpc:
          enabled: true
          grpc_output.enabled: true
...
