apiVersion: v1
kind: Secret
metadata:
    name: bowling-backup
    namespace: bowling
    labels:
        apps.gitops: bowling-mania
type: Opaque
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:E5DxBNM6kHO4ThrYjy1Dzm7qQXJxvYZ64Cg5LQ==,iv:BiSy/FPC4QE1RwOhx3XE0xiHZG8Zhi5rSUDxnrAyWx8=,tag:/N/lCuES/5/X59Qs5x2ulA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:fqZ7H6Yxmi9Wjmjzs6pX,iv:kB9EvF+6FhEnAZceCuWClrg7SVKx1H5p5Ufd3KekESw=,tag:mLVdonFpR/mhutWEpZO/dg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:+b0NpvOh34N3E6ZVLnmYKul3,iv:3w6YCIMYB/DnnDbhqUkHQlBcKtCeZdNlIjSB6x0AC/8=,tag:LPO0FHqxfazbSqmbJygcPA==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:ZKWNj/8kGL3SRw==,iv:GDe02AfHyKvgE1s9NTHfEn42nC1SKPXjnAL/ReGhRGk=,tag:KrLZqCELIc0H6bJgh7rwZw==,type:str]
sops:
    lastmodified: "2026-08-30T16:41:50Z"
    mac: ENC[AES256_GCM,data:DmI5c/PQEWQscTj51bE3cUTH3tEnX1eteLb4iANT5AIpf7oBfx+qV3SIu5wp8GsNWolngMGtJ49HZP0XTDFxpPy1oxfAMyH6UuJGaBJrOP463rmrq32qF970N+AVZszwsSTcr5QC5J+/VZ8xpzL3e9RQfyj4zDEPWnYYjEM3fNI=,iv:y/9rqTD8GTUvSmdhMKN7vtJFFFacOV7ons7DH+4n+gI=,tag:P+bpESJbiQbSzm0L+AY9Mg==,type:str]
    pgp:
        - created_at: "2026-08-30T16:41:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/6ArD67vj9D93V4c2bBhmzwO6rOtcDcM4dRIhE8c0CDBAP
            6t8hKQhz/B9nCSO6iXT8s+jKx5+i9MkG49ljcOdW5r3vUKR8Ispn+7Ak0Srwh7Q9
            isHt0vLVVkiqZN8GOidorxjYQ8HVRNMQLLfbnKFSgNkSl4tp6Rt02ekFxdkxrOZH
            n6/2b2UxkqkZTqFm/oHd4z6hJec7sb2yr+3e2DTFnwSDL7RfJMLGuTJxThOn6GIv
            EvHrtAji4eOLicZ5bs5nQymXgmJiQLyvGWi+WskZBQUmxUseZwQhJ8UAdeMuEOy/
            FfOADJdeJaqQOZ5xholx1E/M65mRVtIiQr09gqT09rDg04wWzi6Eyikz4kBiE3VN
            x7jvKDYlKX9zW8QDN9RquCVJXV0WGcsP+KVkkI8Rm4odV3Oi1xDvYRlLH9m2O5ty
            jT78fXNQ0TGuf50dq23T97Qy0orWbpG3phGcJxG04c+jFtdbAyV8kETi2X/kUsKg
            o2GnKgigczhoHmJ2fZsAA9sG8bZHn30SIdgn0zYVbvI35PO8WuXchPNwAgqqpj4c
            SHwimM49eIttK5HFUla5oXQBMU1RXczAXNoEVD5C5YcZTZUMj3lUECTw8PNusO9t
            RW3onCHi2HApOw9rkabDE/DWgz3atDJuv21k+xJiKk7JH8lpFtuA+O5MX6Tjvp3S
            WAE+TUJ9+DblzlJBfVDs9W+lLWVhkDlp145rtg3lutK2cVGA4En0AXYjeLIZj1xt
            ylISEAtKIXFysvmL3jSLwwP9jFWxm2MzO6jVqENQJHJXF0J6MZNKjB8=
            =DD1T
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
