---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskd
  name: taskd
  namespace: taskd
spec:
  ports:
  - name: taskd
    port: 53589
    protocol: TCP
    targetPort: 53589
  selector:
    app: taskd
  type: ClusterIP
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  labels:
    app: taskd
  name: taskd
  namespace: taskd
spec:
  action:
    pass: taskd
  listener:
    name: taskd
    protocol: TCP
  upstreams:
  - name: taskd
    port: 53589
    service: taskd
...
