---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: taskd-vol
  namespace: taskd
  labels:
    app: taskd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc
...
