---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: taskd
  name: taskd
  namespace: taskd
spec:
  serviceName: taskd
  replicas: 1
  selector:
    matchLabels:
      app: taskd
  template:
    metadata:
      labels:
        app: taskd
    spec:
      containers:
      - name: taskd
        image: quay.io/brokenpip3/taskd:0.0.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        env:
        - name: TZ
          value: "Europe/Rome"
        envFrom:
        - configMapRef:
            name: taskd-config
        ports:
        - containerPort: 53589
        volumeMounts:
        - mountPath: /var/taskd
          name: taskd-data
      volumes:
      - name: taskd-data
        persistentVolumeClaim:
          claimName: taskd-vol
...
