apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secret
    namespace: wallabag
data:
    SYMFONY__ENV__DOMAIN_NAME: ENC[AES256_GCM,data:vOJ3uIY1Z5uO7Da/WC+DgDndV+ehPHnlOjCEA7WFzWOgPtgn7sqzugVEf32HJ+um,iv:/dz4RqSWIZpN7iAibsZCsdVhmI64pHn3/gwjGeXxRsk=,tag:Mhc+IbbwBXgzmFJZsVr0Mw==,type:str]
    SYMFONY__ENV__REDIS_HOST: ENC[AES256_GCM,data:v73lk+GmCR2gsSzX+i4SDgstzFSdbY/H,iv:+xytQbNB9QKjMgnZL6p9Mz4B673I11Sn7iuHxprKhIY=,tag:Wul/NKp5ZxNa9LZ5x6LVuw==,type:str]
    SYMFONY__ENV__REDIS_PASSWORD: ENC[AES256_GCM,data:GCZwMZGLgfKHA8stfYgeBQ==,iv:2MHg6iOfEWg/lM3URiYJtA/d9UNC7qCO4CtcXbcaCAw=,tag:txDebG23WYLMhfsKdAIrQg==,type:str]
    SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:JpOWrLIzB7pqy3eI7NzXsUnWMrSBmG2Y5bDmoEU4Xsx1k+LkEHdgWA==,iv:wYg5QmCYLy0zPiiUrpqp96DX4trev4n3WQPRUT/aIhE=,tag:72ktFrlb2GnOhRJcLS0NAw==,type:str]
    SYMFONY__ENV__SERVER_NAME: ENC[AES256_GCM,data:doqosB9BEoqWEpVNYOOZ7BE1MOSBtUblARf7K1BDlMsK0oyRlHXW6A==,iv:psg1a325LL2wxBfFuXBL/rHKgJ/TNEfHLyEgIy7PuFw=,tag:0LNzt0493xU9GrZiMMQZgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-23T20:40:08Z"
    mac: ENC[AES256_GCM,data:B/a8Yu2IpdpJ0arjIhIRLLAI6uqTx4uebBxbEjjMZIMb02m5W1JhapGyrQN9G0hCBouFdLeZM9a4k/vZq6G2rDQWbfRWccAzVI7SCdl3ZglEXRW1aPk23yVTOthWW9nXTwgDkXx5Ud/25TBaCL6ebAlgCw46rtT2GF+604zpezM=,iv:qDD5iV81tsoWfV1349RKANzaYI2jQNVUe1bXZhb060g=,tag:kTjFm2Wd138BfO0TjBs5ZQ==,type:str]
    pgp:
        - created_at: "2022-02-23T20:40:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5ARAAiJutudzcklmVMjsxJGHbrDqYSX9OYoXXIJGT83pJSC+H
            XDQ9Z13eQr2ZO88OhZcKXx+1JV0cYK1FDcG2g+twDbUK8X9YRaA8gyXg08JbrJ/6
            VGXI7GdgG2VRLEbfBW/BNxs/NywZEK5SA3B465HWWOJKOC1zMGYaBkMWuosjbRua
            bX4tWMaPSSkKuk9SDqpVKkpmsJIxjqPT9mqDNnFtVsjLHl2ueeLjj0rZTLwyBcBO
            +wk/+CruwZW8Ifrve4Gq05My0jvLHRUGGTotRaLm764jSxQWs+LvMbnthKUnfbDI
            SMVc9dPrAXiMm1rYIsfVnbHUPuQzJ/wL6CM5xCMJjQnV7I2/tE9EkL9OSvzuwvXZ
            pU6tBILSuXHXhtfY0SyzCwFSM9rbk2pW+GKfk6Ep/8z+YAMCS8iquTPBKlcA265P
            t4yPj1e5JHr6CPBfFryxdJrB4l50NwNkT8GNS5AD49qypNLga8CAWTCvZeAVsFBj
            O5BV8Vqd4sRYfH4yhypLWXHZCrVEQThoEhZozV+MbB7eztcjqB2eTv31xIgnKkEv
            gMP4+6HkDXphQJnQUt4ZsLP3I/5OFu0LQUb3zXv2BJ5p1WIkJPGhdTWBhR1NOSd+
            H9NoCXfloq8I2zcovU49tFY1BMK8aORmbLjGSkgc4BBrlQS0/77TA4NJoOErx5TS
            UAEgO+lF8mvsKu6xRoHVHPIKYtPj4KWvSCopFFxh9KtTZbDUh6/eSgdCNe4Qx7YB
            zC5wjC+aTCDGDkms/STd0s6rAhCLMOxcC1sy/ISbkOHj
            =WPQk
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
