apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-gitea
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/gitea
  prune: true
  dependsOn:
    - name: infra-ingress-controller
    - name: infra-datastore-postgres-operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: gitea
      namespace: gitea
