apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-falco
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/falco
  prune: true
  dependsOn:
    - name: infra-ingress-controller
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: falco
      namespace: falco
