apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ci-cd
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./ci-cd
  prune: true
  dependsOn:
    - name: infra
    - name: tekton-pipelines-raw
    - name: tekton-triggers-raw
