---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtt-pvc
  namespace: rtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 100Mi
...
