---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-sigs-metric-server
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metric-server
  namespace: kube-system
spec:
  interval: 10m
  releaseName: metrics-server
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  chart:
    spec:
      chart: metrics-server
      version: '>=3.8.2 <4.0.0'
      sourceRef:
        kind: HelmRepository
        name: kube-sigs-metric-server
        namespace: flux-system
      interval: 10m
  values:
    apiService:
      create: true
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
...
