apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: local-path-provisioner
    namespace: kube-system
spec:
    interval: 30m
    chart:
        spec:
            chart: deploy/chart/local-path-provisioner
            sourceRef:
                kind: GitRepository
                name: local-path-provisioner
                namespace: flux-system
            interval: 10m
    values:
        image:
            repository: ENC[AES256_GCM,data:i3p6V7/+9AD11DWn4KBK6tD7BA4lPCAtUxEB/SZ3kqtswsmWz8fm1Q==,iv:m0+GqeZm9R3c2ktnRKiRY5Zg4fgS+0EKKcXllVMKoPo=,tag:Bszd5dhmwGipQDNGBaI31A==,type:str]
            tag: ENC[AES256_GCM,data:2z1QPfdHmQ==,iv:lOZhLPnEZK71rSWndjHVpDAy41lZtWkupccP85ejhgY=,tag:MYrHMf2k1tSTeVK4y79FEQ==,type:str]
        storageClass:
            create: true
            defaultClass: true
            defaultVolumeType: local
            name: local
            reclaimPolicy: Retain
        nodePathMap:
            - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
              paths:
                - ENC[AES256_GCM,data:6+f1+w3QNIBt+CP6v2aX5Bfja9kl+wQ=,iv:OyW4EE+sYi3btUrCxq4177py9rk9k3TnY6IbkWqI4Fo=,tag:mwYIdvTNILShmQOc9d+OXg==,type:str]
sops:
    lastmodified: "2026-02-01T19:11:05Z"
    mac: ENC[AES256_GCM,data:atZRqbhXv9uK17+EqslMCQ/QcCqQWef8DbZW/RDXqHI06+7tEUInKuPNTeoJxVRoZ1liUSozgYkjgyJGjB+KpP2NKvtBCOZalqwdGx94tFERKazjtcXu00sB2c3mGDIb5j09+oXCbF70VGuRdW4YTYN8bLojOZWYnGYBJBtto4I=,iv:0PzLzcT2pWUOaYH9tbP3fBvZRhX2z0ffBHDqkk7+tKM=,tag:rN0Ogy1sJuRiIW3JzxkKkg==,type:str]
    pgp:
        - created_at: "2026-02-01T19:11:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+McbPAYsMJ2dTA7rApBNmMe+48m5dTnl03+tzmuhRQloY
            hrFA5OAxDyhsP8fhJsx2mY/vFZtRY9X2g+05PNfXE15vLxTIcQk3FHicJ2sAAlmp
            3Bn2/dtdfdu+9JkJIjDaD8y8ctOKMix0qyWQ62py11qvrZ4gqY8iwbvthjFegaTG
            DtQ66ATkTvLaR6bJ+myZgghQb8TYhFviWZrn5w2/NlEGTejjWIXGfr2tczfdhOrd
            wMgHo5+YDFdPAbt7KzSNDFzOW+bMuMU+hD175AEzvsiuspMdd/fZ+/UUm7syobbi
            3I95UkZ6PmKxpLQC7Rb1Uk/+38zqtIyIplKrsvjs312jFHxj14+OM2zxiW3dZSqS
            V4hsBxZNRDRj75eYIstFwRFj9iHfCAeGA/Yji3qdUJyUrHwR6ALxKark+6TsTM4K
            vcwhnFBkFh2qvv8oDdoFXyvvflnwAfkH2px5f5AoHFGKUApNrSVZLsKrfi1oEgEI
            wMBxiyn6wR+1oER+HDmDV2gIGKPXvBcxPUrM7LVQ7GhhWqlTnqJDCuSr9cf8wqZa
            AhbD6bOoweYXmFPfN/MZX/1h1R/u/2+urNDYV5YFLFG8/hBFhGpJfrpfO7a/8D/E
            4wQHE5q0Zbo77zuxu3oLEvC3WITgUlLxbZ+vQKjgyR8Ky/bT9zKibPNclPir16DS
            WAFjjvt++jPA1tJBuq4QZSLwrSCJuSODaH4b+ee1+ixWO7THUijyFw114U9M3gDE
            obDuf9XnUSDwPdQ3C3yAIweM+yODnzZxtOQcmAqZnxKAkEU1vsRxKgc=
            =CRlk
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
