---
apiVersion: v1
kind: Namespace
metadata:
  name: fake-smtp
  labels:
    apps.gitops: fake-smtp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-smtp
  name: fake-smtp
  namespace: fake-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-smtp
  template:
    metadata:
      labels:
        app: fake-smtp
    spec:
      containers:
      - image: quay.io/brokenpip3/fake-smtp:0.0.1
        name: fake-smtp
        ports:
        - containerPort: 10025
          protocol: TCP
        resources: {}
        env:
        - name: "NOLOG"
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fake-smtp
  name: fake-smtp
  namespace: fake-smtp
spec:
  ports:
  - name: "smtp"
    port: 10025
    protocol: TCP
    targetPort: 10025
  selector:
    app: fake-smtp
  type: ClusterIP
...
