apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob-pipelinesrun-cleanup.yaml
- cronjob-taskrun-cleanup.yaml
- etcd-backup/cronjob-etcd-backup.yaml
- etcd-backup/image-auto-etcd-backup.yaml
- telegram-notification-alerts.yaml
- telegram-notification-provider.yaml
