apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
    name: telegram-notification-provider
    namespace: flux-system
spec:
    type: telegram
    channel: ENC[AES256_GCM,data:3ulccqD44T4PyWgfP6U=,iv:2txME5gOgcHYZ4i+AS7x3u+4C5qrzFdym1KCQmIxlTw=,tag:pMBNwrG7klHtBTZOM+GDBg==,type:str]
    secretRef:
        name: telegram-notification-provider-cfg
sops:
    lastmodified: "2026-01-02T13:26:30Z"
    mac: ENC[AES256_GCM,data:JjO7hHbGhwSu5t+2jlqFkA8Dp594UgDgcU4xpgEE63+Asuu1OlcSo6JX69364LhbY4eLj1ag0TpVgal8vPzjuHItMTCuoQo+0vGnIHmIYUG1YAUZ9OJba3PMvDkJMsqAw5TkSXxg16MHANvPHPQr8t3Cay4Lbld4xOcGZMkIdeo=,iv:UI1XI5h2l9yNKvktiblxBzF25IVtSSejDNVgDH3oBRs=,tag:VodswWrMUEG2kNR4K0CSag==,type:str]
    pgp:
        - created_at: "2026-01-02T13:26:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+M6d90c48bcp/ygwYpl8AiPLISxNgPMVueZg09A5Z1D4f
            JC7AjQtwOW2rIa9NMz9LH/s9LAjS9j75bi91rgGTVtj5NdpAPw4pfdLQDahDBusr
            LIeo+DkCBZYBSDlZD67nAGufJCoE2LYTMt5YfITWz8ZRq3Fk2b+kpfZMro0xuVGx
            eY7WrIea0UwiyEkJWjAu9XKbBzl7aAVfbacffx+SegzesNcD6PzvZsr2Z8anjHh0
            8fnwNnnve5dz+nmZ0whZWvmDdqkOCWRQDio8emjrMecgKVywZHjvyQToJ1aNzIPY
            G8ss5HgPRfOmpIY0pg5TzHQNvUNfduFsoY1eU8WzNfviDTf3Lrjabjg4/I4zOd0Z
            Ad8CDYkgURROaSffnw28jD1w77LFO57R8ZD8ik8+6QpAH/KwICsSoTqQ96XtNmYq
            tILd4aQKdelddj/3/igExEqCFNmzoK7tcAONzsgFV8Lq4QcjivEzUwGTr96MjOqN
            HSim4QPAf+GmfxhlzVaB1n5YlJ4iACOYJwIeUdx2R4Cmi3Fg0EBIjh/SEPRkoJXT
            AaUZnj7lHOgc+77ebm91k59H/uKhPhmUTeEWYD/xQmFZlr/ZToXnYZ4JlVmX2s9A
            05+jl5HtIhSteKN4KmQbIohiCzQQmRkSsqAkGEJ+FU7S9RDSNHN1XY6vLnPZR+vS
            WAHh+6oa7pxy4AZP2lD7D/wPJZgmRsD8Cx12Q3yxhATT51UWhc/Yc++POq1ulVMo
            OGgN0QZyqlKo6b9lbqeaH57iVRJuBsNCz5wPorMrlzHP5ayaMZD2U5Q=
            =gEwO
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    address: ENC[AES256_GCM,data:jTuzpZ7xhsb08FmvPGjjgLsbMhJ083u4,iv:IsoplzRCDC14s3510uh8NIEQcKWoP1hAcG6DxcNjjCc=,tag:3kuzqGfaMOqC8fzazl30RQ==,type:str]
    token: ENC[AES256_GCM,data:WedoousuZUKCwfbkiX8iomjdaoxUZM6PIbYPcJ4smzDzN2syBAka+K0Dgv5bUQ==,iv:KsyiOxVCzOxfk3In7lq0qZe6qw1Z1ZLrJ/Sk9JCWHw0=,tag:T0kt8jjjNwV/wivjlw6wNg==,type:str]
kind: Secret
metadata:
    name: telegram-notification-provider-cfg
    namespace: flux-system
sops:
    lastmodified: "2026-01-02T13:26:30Z"
    mac: ENC[AES256_GCM,data:JjO7hHbGhwSu5t+2jlqFkA8Dp594UgDgcU4xpgEE63+Asuu1OlcSo6JX69364LhbY4eLj1ag0TpVgal8vPzjuHItMTCuoQo+0vGnIHmIYUG1YAUZ9OJba3PMvDkJMsqAw5TkSXxg16MHANvPHPQr8t3Cay4Lbld4xOcGZMkIdeo=,iv:UI1XI5h2l9yNKvktiblxBzF25IVtSSejDNVgDH3oBRs=,tag:VodswWrMUEG2kNR4K0CSag==,type:str]
    pgp:
        - created_at: "2026-01-02T13:26:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+M6d90c48bcp/ygwYpl8AiPLISxNgPMVueZg09A5Z1D4f
            JC7AjQtwOW2rIa9NMz9LH/s9LAjS9j75bi91rgGTVtj5NdpAPw4pfdLQDahDBusr
            LIeo+DkCBZYBSDlZD67nAGufJCoE2LYTMt5YfITWz8ZRq3Fk2b+kpfZMro0xuVGx
            eY7WrIea0UwiyEkJWjAu9XKbBzl7aAVfbacffx+SegzesNcD6PzvZsr2Z8anjHh0
            8fnwNnnve5dz+nmZ0whZWvmDdqkOCWRQDio8emjrMecgKVywZHjvyQToJ1aNzIPY
            G8ss5HgPRfOmpIY0pg5TzHQNvUNfduFsoY1eU8WzNfviDTf3Lrjabjg4/I4zOd0Z
            Ad8CDYkgURROaSffnw28jD1w77LFO57R8ZD8ik8+6QpAH/KwICsSoTqQ96XtNmYq
            tILd4aQKdelddj/3/igExEqCFNmzoK7tcAONzsgFV8Lq4QcjivEzUwGTr96MjOqN
            HSim4QPAf+GmfxhlzVaB1n5YlJ4iACOYJwIeUdx2R4Cmi3Fg0EBIjh/SEPRkoJXT
            AaUZnj7lHOgc+77ebm91k59H/uKhPhmUTeEWYD/xQmFZlr/ZToXnYZ4JlVmX2s9A
            05+jl5HtIhSteKN4KmQbIohiCzQQmRkSsqAkGEJ+FU7S9RDSNHN1XY6vLnPZR+vS
            WAHh+6oa7pxy4AZP2lD7D/wPJZgmRsD8Cx12Q3yxhATT51UWhc/Yc++POq1ulVMo
            OGgN0QZyqlKo6b9lbqeaH57iVRJuBsNCz5wPorMrlzHP5ayaMZD2U5Q=
            =gEwO
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
