---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zulip-rabbit
  namespace: zulip
spec:
  interval: 10m
  releaseName: zulip-rabbit
  chart:
    spec:
      chart: rabbitmq
      version: '8.22.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    auth:
      username: zulip
      existingPasswordSecret: zulip-secrets
    clustering:
      enabled: false
    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 300m
        memory: 350Mi
    persistence:
      enabled: true
      storageClass: nfs-sc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        rules:
          - alert: RabbitmqDown
            expr: rabbitmq_up{service="{{ template "rabbitmq.fullname" . }}"} == 0
            for: 5m
            labels:
              severity: error
            annotations:
              summary: Rabbitmq down (instance {{ "{{ $labels.instance }}" }})
              description: RabbitMQ node down
          - alert: OutOfMemory
            expr: |
              rabbitmq_node_mem_used{service="{{ template "rabbitmq.fullname" . }}"}
              / rabbitmq_node_mem_limit{service="{{ template "rabbitmq.fullname" . }}"}
              * 100 > 90
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: Out of memory (instance {{ "{{ $labels.instance }}" }})
              description: |
                  Memory available for RabbmitMQ is low (< 10%)\n  VALUE = {{ "{{ $value }}" }}
                  LABELS: {{ "{{ $labels }}" }}
          - alert: TooManyConnections
            expr: rabbitmq_connectionsTotal{service="{{ template "rabbitmq.fullname" . }}"} > 1000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: Too many connections (instance {{ "{{ $labels.instance }}" }})
              description: |
                  RabbitMQ instance has too many connections (> 1000)
                  VALUE = {{ "{{ $value }}" }}\n  LABELS: {{ "{{ $labels }}" }}
...
