---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metric-server
  namespace: zulip
spec:
  interval: 10m
  releaseName: zulip-mem
  chart:
    spec:
      chart: memcached
      version: '5.15.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    resources:
      limits:
        cpu: 300m
        memory: 3508Mi
      requests:
        cpu: 100m
        memory: 156Mi
    persistence:
      enabled: true
    metrics:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      serviceMonitor:
        enabled: true
...
