---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: zulip-exporter-upstream
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/brokenpip3/zulip-exporter
  ref:
    branch: main
  ignore: |
    /*
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: zulip-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: apps
      namespace: flux-system
  interval: 10m
  targetNamespace: zulip
  path: ./kubernetes
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: zulip-exporter
      namespace: zulip
  sourceRef:
    kind: GitRepository
    name: zulip-exporter-upstream
    namespace: flux-system
...
