---
apiVersion: v1
kind: ConfigMap
metadata:
  name: urlwatch-urls
  namespace: urlwatch
  labels:
    app: urlwatch
data:
  urls.yaml: |
    ---
    name: "dotdrop"
    url: "https://github.com/deadc0de6/dotdrop/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "i3-wm"
    url: "https://github.com/i3/i3/tags"
    filter:
      - css: ".Box-row:first-child h4 a"
      - html2text
      - strip
    max_tries: 5
    ---
    # My Pkgbuilds
    name: "k2tf"
    url: "https://github.com/sl1pm4t/k2tf/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "loki"
    url: "https://github.com/grafana/loki/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "apacheconfig"
    url: "https://github.com/etingof/apacheconfig/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "bats-detik"
    url: "https://github.com/bats-core/bats-detik/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "pdh"
    url: "https://github.com/mbovo/pdh/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "pagerduty-pyras"
    url: "https://github.com/PagerDuty/pdpyras/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    # Bats framework
    name: "bats-core"
    url: "https://github.com/bats-core/bats-core/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "bats-assert"
    url: "https://github.com/bats-core/bats-assert/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "bats-support"
    url: "https://github.com/bats-core/bats-support/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "bats-file"
    url: "https://github.com/bats-core/bats-file/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    # Taskwarrior and similar
    name: "taskopen"
    url: "https://github.com/jschlatow/taskopen/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "taskserver"
    url: "https://github.com/GothenburgBitFactory/taskserver/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "taskserver-changelog"
    url: "https://raw.githubusercontent.com/GothenburgBitFactory/taskserver/master/ChangeLog"
    max_tries: 5
    ---
    name: "timewarrior"
    url: "https://github.com/GothenburgBitFactory/timewarrior/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "timewarrior-changelog"
    url: "https://raw.githubusercontent.com/GothenburgBitFactory/timewarrior/dev/ChangeLog"
    max_tries: 5
    ---
    name: "taskwarrior"
    url: "https://github.com/GothenburgBitFactory/taskwarrior/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "taskwarrior-changelog"
    url: "https://raw.githubusercontent.com/GothenburgBitFactory/taskwarrior/develop/ChangeLog"
    max_tries: 5
    ---
...
