---
apiVersion: v1
kind: ConfigMap
metadata:
  name: urlwatch-urls
  namespace: urlwatch
  labels:
    app: urlwatch
data:
  urls.yaml: |
    ---
    name: "dotdrop"
    url: "https://github.com/deadc0de6/dotdrop/releases/latest"
    filter:
      - css: "#repo-content-pjax-container h1"
      - html2text
    max_tries: 5
    ---
    name: "i3-wm"
    url: "https://github.com/i3/i3/tags"
    filter:
      - css: ".Box-row:first-child h4 a"
      - html2text
      - strip
    max_tries: 5
    ---
...
