---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: urlwatch
  name: urlwatch-cache
  namespace: urlwatch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc
  volumeMode: Filesystem
...
