---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    infra.gitops: prometheus
    prometheus: scrape
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promethues-stack
  namespace: monitoring
spec:
  interval: 10m
  releaseName: prom
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '18.0.4'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  values:
    commonLabels:
      infra.gitops: prometheus
    defaultRules:
      rules:
        alertmanager: false
        kubeApiserverAvailability: false
        kubeApiserverError: false
        kubeApiserverSlos: false
        network: true
        kubeScheduler: false
        etcd: false
    grafana:
      enabled: false
    kubeProxy:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus-node-exporter:
      extraHostVolumeMounts:
        - name: text-file
          hostPath: /var/lib/node_exporter
          mountPath: /var/lib/node_exporter
          readOnly: true
          mountPropagation: HostToContainer
      extraArgs:
        - --collector.textfile.directory=/var/lib/node_exporter
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus: scrape
        ruleSelectorNilUsesHelmValues: false
        ruleSelectorNamespaceSelector:
          matchLabels:
            prometheus: scrape
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus: scrape
        probeSelectorNilUsesHelmValues: false
        probeSelectorNamespaceSelector:
          matchLabels:
            prometheus: scrape
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-sc
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-sc
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
...
