apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: basearch-git
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://git.k.brokenpip3.com/ci-cd/docker-makepkg
