apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: basearch-image
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: quay.io/brokenpip3/k8s-fake-smtp
