apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fake-smtp-git
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/brokenpip3/k8s-fake-smtp
