---
apiVersion: v1
kind: Namespace
metadata:
    name: minio
    labels:
      infra.gitops: minio-operator
      prometheus: scrape
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
    name: minio-operator
    namespace: flux-system
spec:
    interval: 5m
    url: https://operator.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: minio-operator
    namespace: minio
spec:
    interval: 10m
    releaseName: s3
    dependsOn:
    - name: nfs-sc
      namespace: kube-system
    chart:
        spec:
            chart: minio-operator
            sourceRef:
                kind: HelmRepository
                name: minio-operator
                namespace: flux-system
            interval: 10m
    values:
      console:
        replicaCount: 1
      tenants:
        - name: pg-backup
          namespace: minio
          pools:
            - servers: 1
              volumesPerServer: 1
              size: 10Gi
              storageClassName: nfs-sc
              secrets:
                enabled: true
              metrics:
                enabled: true
...
