---
apiVersion: v1
kind: Namespace
metadata:
    name: minio
    labels:
      infra.gitops: minio-operator
      prometheus: scrape
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: minio-operator
    namespace: flux-system
spec:
    interval: 10m
    url: https://operator.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: minio-operator
    namespace: minio
spec:
    interval: 10m
    releaseName: s3
    dependsOn:
    - name: nfs-sc
      namespace: kube-system
    chart:
        spec:
            chart: operator
            version: '>=6.x.x <7.x.x'
            sourceRef:
                kind: HelmRepository
                name: minio-operator
                namespace: flux-system
            interval: 10m
    values:
      operator:
        image:
          repository: docker.io/minio/operator
      env:
        - name: WATCHED_NAMESPACE
          value: "minio"
      console:
        replicaCount: 0
      tenants: []
...
