apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-minio
    namespace: minio
    annotations:
        nginx.org/ssl-services: minio
        nginx.org/client-max-body-size: 0m
        nginx.org/rewrites: serviceName=minio rewrite=/
spec:
    tls:
        - hosts:
            - ENC[AES256_GCM,data:QLJBmVyVgvMeshNoVSEceB3kDhg=,iv:tujVLFaNqLvkMsVgY4j+KZn5zK6c8RKqiWzF0QcNq0c=,tag:lO+aHgp/I8TJJ2wLnAad2Q==,type:str]
          secretName: minio-tenant-s3-cert
        - hosts:
            - ENC[AES256_GCM,data:u+PqepCiPt2RjU49484vxegkgR93t6MaVYE2,iv:HxLQ+HyOcYWH0C9vBXAjF1nwl9gFvC6ynSnq3bfdeEI=,tag:6E8try0Feg+TL/R2tZRJnA==,type:str]
          secretName: minio-tenant-s3-cert
    rules:
        - host: ENC[AES256_GCM,data:ra3D/gpyWGuYb5nOOv3iR+9cvPM=,iv:SVun8b60iGPSyRQ/CeIbK7W6KEHWlBORTW2TzDg68Ao=,tag:0QntI7LAziRZPsIu6T9mRA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: minio
                        port:
                            name: https-minio
        - host: ENC[AES256_GCM,data:1Uy8R/2mKq+P9ixL0usz/igaC5vT9Chrfsog,iv:CVaF/hwgUr9cLhLJvQhRq0b838jYfejP57KxdMtwX1A=,tag:m0HbyF5/jECALkIJty8ldA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: minio
                        port:
                            name: https-minio
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-10T16:19:52Z"
    mac: ENC[AES256_GCM,data:SMkxdSc5+8cIu6CEg/3HHECt5CZQ4+q7PSnPDcW3kw/RmFH1S3z9qtN4tTuHhY6slpXsawHpN/uWmAmv+bGeGhqkf+2V/sZw8LgUhf9CRihDExqLMYVN1bQYeBCNTIypHkWKV/bKP5140YP9JqNYUWUjMRFHuncHqMV1IDY2HdM=,iv:aZX10bVZjzVxSHHiY3ic3sBP/S0Jtrb7tlaGkUz5OT0=,tag:nvLpZD61QrneQR2QUlff3A==,type:str]
    pgp:
        - created_at: "2024-11-03T14:26:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+N1JFsRP0i3bi+sjrpUnCITRX9kuY9AAMq7j1f0kAcytk
            rC9uv3eTvdbvk0qcupK12NwNQ+3FJ4SqoyPiPi43445hyeEDBee6Qp9GfGmXwbuX
            hgWdwvvQv7VSD31zfn7WvzppUB9cYIBrYIfxFHxguLL0S2EEouJQE38cD9ejfllg
            i8FN7bZX6wAQOxnajgZ01VUB5W1EUgStg+q6o0Zn+zSCeGBdLJQJQ5eZTINVO117
            V66O7YfPfh+RIXtb5l5kKXjagBhf7rvTtKp6TTBtm2agwlYmjNaovNWgT2OM1+LO
            9AAAEwH5TsK6ovtzngaftXsjDJuDobT/LGjJhXXzacHrKe5R5HpaJTJsmwf2K5lP
            Ybx0hLZPJ9IryR+yyahyi6ULqYLoa4RTsbwBldY4VJtZaC/FSPMkfkEYb+5fLBly
            udW8Vwgn9XPMbj/GqjGgqDPiI5M+IkPE/QoPNjKlBIJtk9Aygm8VGhDHSdtdHBWh
            Odvkr7O4djkg/+NSoRhGukEzn8FfT+6KgFZeAAo1/A2T9F3rUm7StotWcjOk8mlV
            2GTNiDwr4NO+JFg/vuczVY6UnVfPFAbaxo7f83ryAEP40kMHnwFaJaA1VJulQ/ad
            APJXLBKyIFVLZBwPlpbYK3x461uA54K7M3sFMihnM4hsdu7EaH3BQcxyqnWv3kXS
            WAGJTv6J9656yKkNcdfdqyKsHWHJrzJFa7A19m8Zy9+C3EDW7KpLT+7NXFmzS89W
            QP4VeBPKn8sswqKnDcBOPXmfbbfG8RqHYodYNMKzr+gpRzoitX1yWsY=
            =sHef
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.9.0
