apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-s3
  namespace: minio
  labels:
    app: minio
    tenant-scope: s3
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  image: quay.io/minio/minio:RELEASE.2025-02-07T23-21-09Z #{"$imagepolicy": "flux-system:image-policy-minio"}
  configuration:
    name: minio-tenant-s3
  pools:
    - servers: 1
      name: "pool"
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 1Gi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        fsGroup: 1000
  mountPath: /export
  externalCertSecret:
    - name: minio-tenant-s3-cert
      type: kubernetes.io/tls
  requestAutoCert: false
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  prometheusOperator: true
  features:
    bucketDNS: false
  buckets:
    - name: pg-backup
