---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines-raw
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: tekton-pipelines-raw
  timeout: 3m0s
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
  patches:
    - patch: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: tekton-pipelines
          labels:
            infra.gitops: tekton
            prometheus: scrape
      target:
        kind: Namespace
        name: tekton-pipelines
  dependsOn:
    - name: infra
...
