---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter-ha
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: application
        operator: In
        values:
          - spilo
      - key: spilo-role
        operator: In
        values:
          - master
  podMetricsEndpoints:
    - port: exporter
...
