---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux2-upstream
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/fluxcd/flux2-monitoring-example
  ref:
    branch: main
  ignore: |
    /*
    !/monitoring/configs/podmonitor.yaml
    /monitoring/configs/kustomization.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podmonitor-flux
  namespace: flux-system
spec:
  interval: 10m
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-upstream
  patches:
    - patch: |-
        apiVersion: monitoring.coreos.com/v1
        kind: PodMonitor
        metadata:
          namespace: flux-system
      target:
        kind: PodMonitor
        name: flux-system
...
