---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: jenkins-rules
  namespace: monitoring
spec:
  groups:
  - name: jenkins
    interval: 5m
    rules:
      # https://joostvdg.github.io/blogs/monitor-jenkins-on-k8s/alerts/
      - alert: JenkinsTooManyJobsQueued
        expr: jenkins_queue_size_value{service="jenkins-operator-http-jenkins"} > 30
        for: 120m
        labels:
          severity: notify
        annotations:
          summary: " {{ $labels.app_kubernetes_io_instance }} too many jobs queued"
          description: "{{ $labels.app_kubernetes_io_instance }} has {{ $value }} jobs stuck in the queue"

      - alert: JenkinsTooManyJobsStuckInQueue
        expr: jenkins_queue_stuck_value{service="jenkins-operator-http-jenkins"} > 5
        for: 120m
        labels:
          severity: notify
        annotations:
          summary: " {{ $labels.app_kubernetes_io_instance }} too many jobs queued"
          description: " {{ $labels.app_kubernetes_io_instance }} has {{ $value }} jobs in queue"

      - alert: JenkinsHealthScoreToLow
        expr: jenkins_health_check_score{service="jenkins-operator-http-jenkins"} < 1
        for: 10m
        labels:
          severity: notify
        annotations:
          summary: " {{ $labels.app_kubernetes_io_instance }} has a to low health score"
          description: " {{ $labels.app_kubernetes_io_instance }} a health score lower than 100%"

      - alert: JenkinsTooManyPluginsNeedUpate
        expr: jenkins_plugins_withUpdate{service="jenkins-operator-http-jenkins"} > 20
        for: 10m
        labels:
          severity: notify
        annotations:
          summary: " {{ $labels.app_kubernetes_io_instance }} too many plugins updates"
          description: " {{ $labels.app_kubernetes_io_instance }} has {{ $value }} plugins that require an update"

      - alert: JenkinsVMMemoryRationTooHigh
        expr: vm_memory_heap_usage{service="jenkins-operator-http-jenkins"} > 0.70
        for: 3m
        labels:
          severity: notify
        annotations:
          summary: "{{$labels.app_kubernetes_io_instance}} too high memory ration"
          description: "{{$labels.app_kubernetes_io_instance}} has a too high VM memory ration"
...
