apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-authentik
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/authentik
  prune: false
  dependsOn:
    - name: infra-storage
    - name: infra-datastore-postgres-operator
    - name: infra-ingress-controller
    - name: infra-certmanager
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: authentik
      namespace: authentik
