---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-prometheus
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/prometheus/
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-prometheus-monitors
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/prometheus/prom-crds
  prune: true
  dependsOn:
    - name: infra-prometheus
...
