apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-certmanager
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/certmanager/
  prune: true
