name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Check for updates
        id: update
        run: |
          flux install --components-extra=image-reflector-controller,image-automation-controller \
            --export > ./clusters/private-contabo/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          VERSION_INT="$(flux -v | awk '{print $3}')"
          echo "flux_version=$VERSION" >> $GITHUB_OUTPUT
          echo "flux_version_short=$VERSION_INT" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: update-flux
            delete-branch: true
            assignees: "brokenpip3"
            labels: "auto-cluster-update"
            commit-message: Update to ${{ steps.update.outputs.flux_version }}
            title: Update to ${{ steps.update.outputs.flux_version }}
            body: |
              ${{ steps.update.outputs.flux_version }}
              [Release notes](https://github.com/fluxcd/flux2/releases/tag/v${{ steps.update.outputs.flux_version_short }})
