name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  pre-commit:
    name: PreCommit
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17
      with:
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      with:
        diagnostic-endpoint: ""
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: nix checks
      run: nix flake check
    - name: nix pre-commit
      run: nix develop . --command pre-commit run --show-diff-on-failure
