name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  pre-commit-update:
    name: PreCommitHooksUpdate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
