name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  pre-commit-update:
    name: PreCommitHooksUpdate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@c00c8a7e841303c35ca3f9d1f4ec543296de23e6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
