name: image-update-auto-pr
on:
  workflow_dispatch:
  push:
    branches: [images-update-etcd, images-update-minio]

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      name: checkout

    - uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Updating ${{ github.ref }} into main"
        pr_body: "Automated image update PR*"
        pr_reviewer: "brokenpip3"
        pr_label: "auto-image-update"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
