#From: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/.github/workflows/test.yaml

name: flux-validate

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Validate manifests
        run: ./scripts/github/validate.sh
