apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
    name: gitea
    namespace: gitea
spec:
    rules:
        - host: ENC[AES256_GCM,data:ybP1GDWf6NTjipErq2/iY0D/s3Gx,iv:PSFYVGN4+UvGdFhhwN7kYJmFuLn+2sFt2MUgeFyURaI=,tag:mRJipQmhBPw1hi9ZM78Dww==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: gitea-service
                        port:
                            number: 3000
                  path: /
                  pathType: ImplementationSpecific
    tls:
        - hosts:
            - ENC[AES256_GCM,data:IIAWUa7g7TiOPB4YrvRAdiGGGzE3,iv:PVUZRzISncuANjDFo4lA3RSvx7qVMAqbmVcUhdGNeUU=,tag:A5brbkV8d8BNflabGiNAXw==,type:str]
          secretName: gitea-ingress-tls-cert
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T21:21:29Z"
    mac: ENC[AES256_GCM,data:INuvDksuzU8mladqG1gR6zRYHsQQotH9M+aaJnHTB010wAW+4PAt3tDfJe6JfdteBiYNKFVWsh70nr361SqxQhMcVNakI8PiYzJv+3YV6U+nJ7RbqPwW4DxBwPVagbt3O+j4VuxB2BEWkLVo97mQb2E0gVIW8X5GwGWXjfAoy3c=,iv:A7Hb+WwBtCIMKs6a/WFx87g83tGDQfaWqEt366Fm/m4=,tag:eOuhwJ1xaAg+5fax/Wl6dA==,type:str]
    pgp:
        - created_at: "2021-09-03T21:21:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILAwP8FxNnerN5AQ/2Pw/EP0q/xqaZ4TMmLXJ42aHvN33rYns3UKPTjD7xB1zl
            8szQZ3R5AukoEK2blI+j4rOebX6ai7OEvgGF77hLNkxI5R/zXNmBT3m87lCq8bUC
            /tsKgoHmftoxmFpDv6gR5+WhcYbkOxIyJyiRv88N9hCXQQZpMUmcFYwPfDrk4p9S
            Ninn+9ScfN/9LmtYhuzdDkHFnwbNxW4wPMC+X9Pl0tb0JlYIY8sSwMst/qIxDDdK
            ki/pj8TtvBVyamNXOGzrN4ddrbkMgAXO635bY+d1/NHWHymtk/XOw6s0QTaQREss
            t1HxFLULI9O6EyMkhOwfiTZBqJ3dgil5hAJxxu4w+ZW/H+iacppKMEzgXnTPJm4D
            r0c8KewC2ZBeggy2ZsbDQQ1LAULUtDmKTV+TetHAh5s1c+1XAPWRF1YK8M5AG6CX
            OHZXH+eGsbVoakztgItsFwAcdMEVFUtnbC6g9dPFJIgPzLdjPsr4ZuyBJvvWNz1o
            TvVdj0UnN5+2m0lNOHnrRGoF14n3TKGUJ0FnvI3ajVEuAxagG1hMIKkU5LQfLIhR
            0iadgDbX36/eqxjfcDHsMXV08PfBU9aABUE+eUCDTKvIup9sT/JLcuFkZ/ZIBVe2
            JjSfPEo50aoyGOLhsMwyeRL9KoSvbq9QV9/D9blA1g7v5ywvrA8eGOiH7K+J4dJQ
            AS5wv8D4Crm9NFWM/q+RrZYW1LQf8V15bNsR0a8aPJdZcaDkIKI516ILnvERc0mm
            WU69sdEBFtpS2QpZMdnBEaAjVtFZ6Mtf4TJ9n/DwmHU=
            =0XgA
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
