apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
    name: gitea
    namespace: gitea
spec:
    rules:
        - host: ENC[AES256_GCM,data:4nM8qclh/9YAn2Bh6RC0NQZwSP7U,iv:7k4FXYkb93foaHahvPo5uFzG86XLrUgzBhDKmHEGmuI=,tag:0LuSLtzg3IEx+qh351/mOw==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: gitea-service
                        port:
                            number: 3000
                  path: /
                  pathType: ImplementationSpecific
        - host: ENC[AES256_GCM,data:oYpH0lfcgtFGCAuZgIWN2U3Om9Q=,iv:QBPwxwceEM0LByY8SOSYSKR2EF9erYAH6qMZ4VVZlaU=,tag:nFPqqYQWo5oRcYxakYM85w==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: gitea-service
                        port:
                            number: 3000
                  path: /
                  pathType: ImplementationSpecific
    tls:
        - hosts:
            - ENC[AES256_GCM,data:BpQpY4sLAjlfZ5Z/gYkFCCR4ERkx,iv:XwlJEzTZTngEwZEFrQ1Fx+4kI9J06Qk8KQrtvxWp7Uc=,tag:JaDYOko3+M6Z60cX3bYJcA==,type:str]
          secretName: gitea-ingress-tls-cert
        - hosts:
            - ENC[AES256_GCM,data:xWjk5YcU1KrdpeSS1t6QyetNmU0=,iv:ZXlYQyXb/8vT/MHjmxa59S/4uZJgoGO1NOJbaqwtRXQ=,tag:Ry9w8DXvXvgafGoqZvtOyg==,type:str]
          secretName: gitea-ingress-tls-cert
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T22:04:11Z"
    mac: ENC[AES256_GCM,data:Bma5O2e8Yr6M33FMilIVP2J5v14TJ+dI26/eKdkkn/7eV7WBhIpI/cREfOplQrYg6SNi3T63GBV4N7gvZSqduI20fE7Vx+N6Ycg/YvsGB3uiHi/YBZuGTT5BtvAkWAnwqj+CtEbf4LLD008FKPhRZxeKgDm4ZnVbm28njEuPKkk=,iv:WTiqeN9jHJc+q9iWKX33dYGAtjABzTbbXhT9HCvSu3Y=,tag:qL8dyF9ZE3s7AXmuzUexPA==,type:str]
    pgp:
        - created_at: "2021-09-03T22:04:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ/+Nemc2qi3IZSpIjA94wbdMMJTIdI419HtiahGBAeBSv+K
            ker8wbi6j/ju2hz4JWzfoKUTIjoG2EA49Yxp53IhFVZwKXoyk99qrPAGxN0rJVQS
            DvsusDYeJ/KypeqLRRSc5QujZ3zDlqwdvf68Bi+qhHsOHeT5uMNmWzuhhz7FqJ1l
            AxO1zW+KKIW6e+hgZsXTHI/v7BvtKWHYHQZFMDuJw2h8ftBfDSyGW38b5L7DZU0u
            rkfMIDNbxpn5sUvan0O29DwP6Ht84zd3HgVH9NDhCYi91TGQT9e1JJYQy470WA7d
            KpVciNmU5tBAHRHJKEA3jDjgR/GamULwG9a9kYipLE18tF1/wl0ICKTobM23B/lb
            y4Z2AYBSWdII2+VNsv1o1eIOF0oJrNnQSzX3BvIqjpWl/9+4oKHL/e7WPUPxLeIL
            k+ItxVjHAXYUZS4ayo222YIPtTtwMECUV4D2z1DgbzDD80e1jvn3tb7sWtZb6WrU
            2iBD8Fq3qmnxnImjOx2lQ/38L78kC2n+U1bXFn5wqGgcaWw/MYDBh5kqYNX4s72V
            4rqE4F7xnwLEtXCOYqQqxybYNc3H16K1+d0bZx2RcrG2kT6pHiFDLuH5Y0geid5r
            tskCJECGfBASvxhOTL0E0jRXjL5RW4a4KUaBY+utCllL7BbuNZ7mR0FVlMHFkHDS
            UAHuppBEpFCudP5K/a3JH44Zg5akAnNz/cFzQLzeEo6fnOxv3n28JIApQp25yPLy
            YcvhfcAls1vUGlZO1NDc7+6xQ6KJFrhtMxZmUWWNlP7H
            =45Cv
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|dnsNames)$
    version: 3.7.1
