---
apiVersion: v1
kind: Namespace
metadata:
    name: gitea
    labels:
      apps.gitops: gitea
      prometheus: scrape
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - env:
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              key: password
              name: gitea.gitea-gitea.credentials.postgresql.acid.zalan.do
        envFrom:
        - configMapRef:
            name: gitea-values
        image: docker.io/gitea/gitea:latest
        imagePullPolicy: Always
        name: gitea
        ports:
        - containerPort: 3000
          name: gitea-http
          protocol: TCP
        - containerPort: 22
          name: git-ssh
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: gitea-http
          initialDelaySeconds: 200
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: gitea-http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: git-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-data
        persistentVolumeClaim:
          claimName: gitea-data
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea
  labels:
    app: gitea
spec:
  ports:
  - name: gitea-http
    port: 3000
    protocol: TCP
    targetPort: gitea-http
  selector:
    app: gitea
  sessionAffinity: None
  type: ClusterIP
...
