apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  namespaceSelector:
    matchNames:
      - gitea
  selector:
    matchLabels:
      app: gitea
  endpoints:
  - port: gitea-http
