apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotb
  namespace: lotb
  labels:
    app: lotb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lotb
  template:
    metadata:
      labels:
        app: lotb
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: lotb-app
        image: ghcr.io/brokenpip3/lotb:0.0.0-dev
        args: ["lotb", "--config", "/tmp/config.toml"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: lotb-envs
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1024Mi"
        volumeMounts:
        - mountPath: /lotb/data
          name: data
        - mountPath: /tmp/config.toml
          name: lotb-config
          subPath: config.toml
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lotb-data
      - name: lotb-config
        secret:
          secretName: lotb-config
