apiVersion: v1
kind: Secret
metadata:
    name: lotb-backup
    namespace: lotb
    labels:
        apps.gitops: lotb
type: Opaque
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:t9ABV6nsep+V+Aj1XsYRIJz/K6XwPTZg3LrU+A==,iv:jY+oSXJXj342qK2UYnwaeZMa4/TdJL8CFA1oh+UBHbE=,tag:Z+0h4Nhoeo790mLujZtI6w==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ljTZ8hmaveuvdmcZj9+1,iv:byVkgVOlVkxWJB1NDiWtm1fSbYvwoSaqFekCg2utUfU=,tag:3sOiEPKfJW6g5vCFfJFuZA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:znci+IkUzJHhzZGH+q7nnWX+,iv:n8E/gL7T66TTVsYItz5hdkS7YTVPdtN2T1MxwWYAnAk=,tag:AX6Oyd02r5ab5YtEd32DAA==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:KDml6vNUwZ3y66w=,iv:vwY7hcQz1aW9qHVjguAcwgJBolwCV4YCQRoXpci7/PA=,tag:s63Xjqqv8v/JcLpfXmZ+pw==,type:str]
sops:
    lastmodified: "2026-08-30T16:11:55Z"
    mac: ENC[AES256_GCM,data:ioy0H/W0bIVYBLvr7pWVgp0SKPeiBiC4n3z6etHIY+7NHeU0Rb0/SB8c7FpoF1HjvRUmExLsXVJcPgXYdnYU3JzSWqLhFsdEQw2LEeUdXbPnz1a0PHluLKpWz+jDr1S+ofuPggrxgg3ZIorAwgzhOzMIL9L4ImpXaDr5S5m4XhY=,iv:0bJkMQmcx0d4Boa02xSE+3z7P2HF49NbjfdgLuXyplo=,tag:DZy5AuZ7DZxONIOatD/bXg==,type:str]
    pgp:
        - created_at: "2026-08-30T16:11:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwP8FxNnerN5AQ//TukIak/PiaIeWmVtPcmX5zvOpd+F94aGC8XbbxphZhcF
            SRX5jQDimOlCwx2MgbLsaKOoSFGVK65fq200p0BmUZ8AiEjlMDjMfm/H5oZlihBs
            E2pIdlEisJRW4DSTGMRFkyqDmdtDpjg/nT7Jg3UCoJeuS7RLXD0RukvSagqmKznq
            dI7oDtXPIgWklDbVKDCbUfn306pChI/uF424I5fgjsMsUA4WDzpo9/IWC9buA6Bl
            IR6Xqw3P6o9Vv298zo8Sg0rc68qo0snpf8SV+188ePivEZnVs1AUU0WNY3qPNy4y
            lRqGRcjTfcFqsv60QA8wUhEKl/zKslyobAOLTlM7cUzDdtYlqK22EBVywL3Widhz
            tQseORwB4pY3//gJx6FXLsy2rcWykR4FTZrDUJOacXQIl/u9spxV18laQ0vUB+Gx
            d/qiUDKthWJVtrEsI11aid8tw8I0hxtpory5z+3LzdHAWd/lfzuKYFq7Jd5JW5FC
            m2MOw3gGNglWtmhf+2xf/FzPttCeT2gBsZl1wQ3G9j81X6kX1yZtnaW4NS4vJcIv
            B/oW9pzaIov3Hp8EXkhcNhcJG7EI6hzHMnvZo1+QuAGfSuvryI5WzwJ1WO2YzRSu
            Qlv9b2kipmGZY2AfTfGf64snvRD6J81PICxNqRsJq/Z24F/SgvLK7sgLHG0mdKXS
            WAHdTEcV2lSj7a/3tP0wguNRmIe575ZBY+GKPuV7VZKA48guwopVqTdxWvOOmI2e
            /KB/mRRyhmKpDnKTGJ3tBW2qVa20XzkurzkPHJIeMyYThXXlowJnr54=
            =XmMx
            -----END PGP MESSAGE-----
          fp: FEE43962AC34E28FB078EFA9F6C9CFE02626638C
    encrypted_regex: ^(data|stringData|consumerKey|email|groupName|applicationKey|host|hosts|server|configLogicalBackup|paths|dnsNames|channel|image)$
    version: 3.11.0
